### ISSUE TITLE
mirai无法启动

### ISSUE THREAD

**Issue by Kevin010304** [mamoe/mirai-console#104]
```
D:\mirai>java -jar mirai-console-wrapper-1.3.0-all.jar
Using proxy: null
You are running Mirai-Console-Wrapper under D:\mirai
All additional libraries are located at D:\mirai\libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.0.0 | Newest STABLE Console-Pure Version: 0.5.2
Updating Console-Pure from V0.0.0 -> V0.5.2

Local Core Version: 0.0.0 | Newest STABLE Core Version: 1.0.3
Updating shadowed-core from V0.0.0 -> V1.0.3
GitHub mamoe.github.io: https://mamoe.github.io/mirai-repo/shadow/mirai-console/mirai-console-0.5.2.jar
GitHub mirai-repo: https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/mirai-console/mirai-console-0.5.2.jar

GitHub mamoe.github.io
GitHub mamoe.github.io: https://mamoe.github.io/mirai-repo/shadow/mirai-core-qqandroid/mirai-core-qqandroid-1.0.3.jar
GitHub mirai-repo: https://raw.githubusercontent.com/mamoe/mirai-repo/master/shadow/mirai-core-qqandroid/mirai-core-qqandroid-1.0.3.jar

GitHub mamoe.github.io
Progress:                                           | 0MB
无法从 GitHub mamoe.github.io 下载. 正在更换下一个源

GitHub mirai-repo

无法从 GitHub mamoe.github.io 下载. 正在更换下一个源

GitHub mirai-repo
Progress:                                           | 0MB
无法从 GitHub mirai-repo 下载. 正在更换下一个源

无法从 GitHub mirai-repo 下载. 正在更换下一个源
Version check complete, starting Mirai
Exception in thread "main" kotlin.KotlinNullPointerException
        at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative$mirai_console_wrapper(WrapperMain.kt:203)
        at net.mamoe.mirai.console.wrapper.WrapperCli.run(WrapperMain.kt:143)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:176)
```

**Comment by Him188** [comment]
请使用 https://github.com/LXY1226/miraiOK
