### ISSUE TITLE
插件构建过程中如使用到了description中的值会报 lateinit property _description has not been initialized

### ISSUE THREAD

**Issue by yyuueexxiinngg** [mamoe/mirai-console#115]
复现代码:
```kt
package tech.mihoyo.mirai

import net.mamoe.mirai.console.plugin.jvm.KotlinPlugin

object TestPluginBase: KotlinPlugin() {
    private val currentVer = description.version

    override fun onLoad() {
        logger.info("Just to show loaded")
    }

    override fun onEnable() {
        logger.info("Enabled with version: $currentVer")
    }

    override fun onDisable() {
    }
}

```
在`0.5.2`中不会发生此错误, 实际应用场景如[mirai-api-http中的此行代码](https://github.com/project-mirai/mirai-api-http/blob/b09938946ef873b2880585911602954e72936095/mirai-api-http/src/main/kotlin/net/mamoe/mirai/api/http/HttpApiPluginBase.kt#L103)
```
2020-08-20 11:47:48 I/main: Starting mirai-console...
2020-08-20 11:47:48 I/main: Backend: version 1.0-M1, built on 2020-08-02.
2020-08-20 11:47:48 I/main: Frontend Pure: version 1.0-M1.
2020-08-20 11:47:49 I/main: Preparing built-in commands: help, stop
2020-08-20 11:47:49 I/main: Loading plugins...
2020-08-20 11:47:49 I/PluginManager: Cannot load plugin TESTPlugin
2020-08-20 11:47:49 W/serr: Exception in thread "main" net.mamoe.mirai.console.plugin.PluginLoadException: Exception while loading TESTPlugin
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.plugin.JarPluginLoaderImpl.load(JarPluginLoaderImpl.kt:102)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.plugin.jvm.JarPluginLoader$INSTANCE.load(JarPluginLoader.kt)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.plugin.jvm.JarPluginLoader$INSTANCE.load(JarPluginLoader.kt:28)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.plugin.DeferredPluginLoader.load(PluginLoader.kt:103)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:62)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAndEnableAllInOrder(PluginManagerImpl.kt:110)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadEnablePlugins$mirai_console(PluginManagerImpl.kt:105)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:90)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:84)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.pure.MiraiConsolePureLoaderKt.startup(MiraiConsolePureLoader.kt:53)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:45)
2020-08-20 11:47:49 W/serr: Caused by: java.lang.ExceptionInInitializerError
2020-08-20 11:47:49 W/serr:     at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
2020-08-20 11:47:49 W/serr:     at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1045)
2020-08-20 11:47:49 W/serr:     at java.base/jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
2020-08-20 11:47:49 W/serr:     at java.base/jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186)
2020-08-20 11:47:49 W/serr:     at java.base/java.lang.reflect.Field.acquireFieldAccessor(Field.java:1105)
2020-08-20 11:47:49 W/serr:     at java.base/java.lang.reflect.Field.getFieldAccessor(Field.java:1086)
2020-08-20 11:47:49 W/serr:     at java.base/java.lang.reflect.Field.get(Field.java:418)
2020-08-20 11:47:49 W/serr:     at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:116)
2020-08-20 11:47:49 W/serr:     at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:62)
2020-08-20 11:47:49 W/serr:     at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31)2020-08-20 11:47:49 W/serr:     at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt)
2020-08-20 11:47:49 W/serr:     at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:241)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.plugin.JarPluginLoaderImpl.load(JarPluginLoaderImpl.kt:86)
2020-08-20 11:47:49 W/serr:     ... 10 more
2020-08-20 11:47:49 W/serr: Caused by: kotlin.UninitializedPropertyAccessException: lateinit property _description has not been initialized
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.get_description$mirai_console(JvmPluginInternal.kt:50)
2020-08-20 11:47:49 W/serr:     at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.getDescription(JvmPluginInternal.kt:52)
2020-08-20 11:47:49 W/serr:     at tech.mihoyo.mirai.TestPluginBase.<clinit>(main.kt:6)
2020-08-20 11:47:49 W/serr:     ... 23 more
```

**Comment by Him188** [comment]
这是正常情况, 请使用 ` by lazy {}`
