### ISSUE TITLE
mirai无法启动，一直尝试拉取Newest STABLE Console-Pure Version: 1.0-M2-1

### ISSUE THREAD

**Issue by hitoridejuyon** [mamoe/mirai-console#124]
使用mirai-console-wrapper-1.3.0-all进行启动，然后就一直尝试拉取Console-Pure Version: 1.0-M2-1，但是在mirai-repo上只有Console-Pure Version: 1.0-M2-all版本，没有匹配的版本，之后就报错退出了，是必须要自己编译这个版本么？
报错信息：
Using proxy: null
You are running Mirai-Console-Wrapper under /usr/local/mirai
All additional libraries are located at /usr/local/mirai/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Fetching Newest Console Version of Pure
Local Console-Pure Version: 1.0-M2-all | Newest STABLE Console-Pure Version: 1.0-M2-1
Updating Console-Pure from V1.0-M2-all -> V1.0-M2-1

Local Core Version: 1.2.2 | Newest STABLE Core Version: 1.2.2
GitHub mamoe.github.io: https://mamoe.github.io/mirai-repo/shadow/mirai-console/mirai-console-1.0-M2-1.jar
GitHub mirai-repo: https://raw.githubusercontent.com/TonnyGe/mirai-repo/master/shadow/mirai-console/mirai-console-0.5.2.jar

GitHub mamoe.github.io
Progress:                                           | 0MB
无法从 GitHub mamoe.github.io 下载. 正在更换下一个源

GitHub mirai-repo
Progress:                                           | 0MB
无法从 GitHub mirai-repo 下载. 正在更换下一个源
Version check complete, starting Mirai
shadow-Protocol:/usr/local/mirai/content/mirai-core-qqandroid-1.2.2.jar
Exception in thread "main" kotlin.KotlinNullPointerException
        at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative$mirai_console_wrapper(WrapperMain.kt:204)
        at net.mamoe.mirai.console.wrapper.WrapperCli.run(WrapperMain.kt:143)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:154)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:14)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:252)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:249)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:267)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:290)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:176)

**Comment by Pai2Chen** [comment]
wrapper不是废除了么，，即使下载成功启动类也改了
可以试一下我自制的端
https://github.com/Pai2Chen/mirai-console-starter

**Comment by Him188** [comment]
wrapper已经停止支持，请使用 miraiok
