### ISSUE TITLE
Internal error: bad indent 0, expected no bigger than -2

### ISSUE THREAD

**Issue by ls148478** [mamoe/mirai-console#149]
启动console的时候报了这个错 还没登录的情况下 所以感觉这应该不是插件的原因 特提出一个Issues
日志：
`2020-09-01 16:07:24 I/main: Starting mirai-console...
2020-09-01 16:07:24 I/main: Backend: version 1.0-M3-1, built on 2020-08-27 22:34:59.
2020-09-01 16:07:24 I/main: Frontend Pure: version 1.0-M3-1, provided by Mamoe Technologies
2020-09-01 16:07:24 I/main: Reloading configurations...
2020-09-01 16:07:27 I/main: Prepared built-in commands: help, login, managers, stop
2020-09-01 16:07:27 I/main: Loading plugins...
2020-09-01 16:07:28 I/plugin: Successfully loaded plugin Test
2020-09-01 16:07:28 I/plugin: Successfully enabled plugin Test
2020-09-01 16:07:28 I/main: 1 plugin(s) loaded.
2020-09-01 16:07:28 I/main: mirai-console started successfully.
2020-09-01 16:17:27 E/Plugin Test: java.lang.IllegalStateException: Internal error: bad indent 0, expected no bigger than -2
java.lang.IllegalStateException: Internal error: bad indent 0, expected no bigger than -2
	at net.mamoe.yamlkt.internal.YamlUtils__YamlWriterKt.writeIndentSmart(YamlWriter.kt:111)
	at net.mamoe.yamlkt.internal.YamlUtils.writeIndentSmart(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:558)
	at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:429)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:96)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:36)
	at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:111)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:63)
	at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:112)
	at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:34)
	at net.mamoe.mirai.console.data.AutoSavePluginData$onStored$5.invokeSuspend(AutoSavePluginData.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
2020-09-01 16:17:27 E/Plugin Test: java.lang.ArrayIndexOutOfBoundsException: Index 39080 out of bounds for length 128
java.lang.ArrayIndexOutOfBoundsException: Index 39080 out of bounds for length 128
	at net.mamoe.yamlkt.internal.YamlUtils__EscapeKt.getQuotationAvailability(Escape.kt:412)
	at net.mamoe.yamlkt.internal.YamlUtils.getQuotationAvailability(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlUtils__EscapeKt.toEscapedString(Escape.kt:350)
	at net.mamoe.yamlkt.internal.YamlUtils.toEscapedString(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeString(YamlEncoder.kt:493)
	at kotlinx.serialization.internal.StringSerializer.serialize(Primitives.kt:179)
	at kotlinx.serialization.internal.StringSerializer.serialize(Primitives.kt:177)
	at net.mamoe.mirai.console.internal.data.StringValueImpl.serialize(_PrimitiveValueDeclarations.kt:368)
	at net.mamoe.mirai.console.internal.data.StringValueImpl.serialize(_PrimitiveValueDeclarations.kt:342)
	at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:422)
	at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:296)
	at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:429)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:97)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:36)
	at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:111)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:63)
	at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:112)
	at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:34)
	at net.mamoe.mirai.console.data.AutoSavePluginData$onStored$5.invokeSuspend(AutoSavePluginData.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)`

**Comment by Him188** [comment]
此问题将在 1.0-M4 修复
