### ISSUE TITLE
在非交互终端内启动console-pure会疯狂报错

### ISSUE THREAD

**Issue by KawaiiZapic** [mamoe/mirai-console#162]
配合某些插件实现自动登陆,mirai-console已经完全不需要交互.  
但是将其作为systemd系统服务时,会一直刷报错直至硬盘爆满:  
```
> 2020-09-11 13:00:30 E/console: Unhandled exception
org.jline.reader.EndOfFileException
         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:639)
         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
         at net.mamoe.mirai.console.pure.ConsoleInputImpl$requestInput$2.invokeSuspend(MiraiConsoleImplementationPure.kt:101)
         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
目前的解决方案只有`>/dev/null`.

**Comment by Karlatemp** [comment]
`console-pure` 重新设计时并没有考虑到无输入终端环境, 感谢您发现这个问题
