### ISSUE TITLE
无论如何也无法启动1.0版本

### ISSUE THREAD

**Issue by Vivapercuore** [mamoe/mirai-console#165]
shadow-Protocol:/xxxxxx/content/mirai-core-qqandroid-1.2.3.jar
Console        :/xxxxxx/content/mirai-console-pure-1.0-M4.jar
Root           :/xxxxxx/
Exception in thread "main" java.lang.NoClassDefFoundError: net/mamoe/mirai/console/MiraiConsoleImplementation
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at net.mamoe.mirai.console.wrapper.MiraiClassLoader.findClass(WrapperMain.kt:275)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)
	at java.base/java.lang.Class.getMethod0(Class.java:3293)
	at java.base/java.lang.Class.getMethod(Class.java:2106)

不知道是哪里出了问题

**Comment by Vivapercuore** [comment]
通过各种方式进行了尝试，都是类似如下的信息：

错误: 找不到或无法加载主类 lib.mirai-console-pure-1.0-M4.jar
原因: java.lang.ClassNotFoundException: lib.mirai-console-pure-1.0-M4.jar

错误: 找不到或无法加载主类 mirai-console-pure-1.0-M4.jar
原因: java.lang.ClassNotFoundException: lib.mirai-console-pure-1.0-M4.jar

现windows能正确运行 
Linux和Mac都如上报错
最终希望的运行环境是Linux

**Comment by Vivapercuore** [comment]
补充：0.5.2版本在windows/mac/linux 环境 都运行正常

**Comment by zhzRedstone** [comment]
```bat
java -cp "./lib/*" net.mamoe.mirai.console.pure.MiraiConsolePureLoader
```
```
D:.
│  start.bat
└─lib
        mirai-console-1.0-M4.jar
        mirai-console-pure-1.0-M4.jar
        mirai-core-qqandroid-1.2.3.jar
```

**Comment by Vivapercuore** [comment]
> ```
> D:.
> │  start.bat
> └─lib
>         mirai-console-1.0-M4.jar
>         mirai-console-pure-1.0-M4.jar
>         mirai-core-qqandroid-1.2.3.jar
> ```
> 
> start.bat:
> 
> ```batchfile
> java -cp "./lib/*" net.mamoe.mirai.console.pure.MiraiConsolePureLoader
> ```

尝试过了，windows能跑，linux不行，mac不行，不信的话我可以给你截图或者你来远程一下....

**Comment by Vivapercuore** [comment]
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Raspbian-1deb10u1)
OpenJDK Server VM (build 11.0.8+10-post-Raspbian-1deb10u1, mixed mode)
 $ ls ./lib
mirai-console-1.0-M4.jar       mirai-core-1.2.3.jar
mirai-console-pure-1.0-M4.jar  mirai-core-qqandroid-1.2.3.jar
 $ java -cp "./libs/*" net.mamoe.mirai.console.pure.MiraiConsolePureLoader $*
错误: 找不到或无法加载主类 net.mamoe.mirai.console.pure.MiraiConsolePureLoader
原因: java.lang.ClassNotFoundException: net.mamoe.mirai.console.pure.MiraiConsolePureLoader

**Comment by Him188** [comment]
https://github.com/LXY1226/MiraiOK

**Comment by Vivapercuore** [comment]
> https://github.com/LXY1226/MiraiOK

尝试过MiraiOK，mirai-console-starter，mirua，都无法在linux和mac上找到主类
确认过文件版本，文件大小，尝试过各种下载方式，和各种启动器以及各种使用java -cp的启动方式
