### ISSUE TITLE
无法更新

### ISSUE THREAD

**Issue by wyapx** [mamoe/mirai-console#18]
![图片](https://user-images.githubusercontent.com/26220729/77341582-e2a9e480-6d69-11ea-82b4-d1de401b5025.png)
错误如图，现在也没办法启动

**Comment by kirainmoe** [comment]
更新 0.3.7 时问题依旧：

```
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.0.0 | Newest Console-Pure Version: 0.3.7
Updating Console-Pure from V0.0.0 -> V0.3.7, this is a force update
Local Core Version: 0.0.0 | Newest Core Version: 0.30.0
Updating Core/Lib from V0.0.0 -> V0.30.0, this is a force update
Failed to download newest Protocol lib, please seek for help
java.lang.IllegalStateException: File not found
        at net.mamoe.mirai.console.wrapper.DownloaderKt.downloadMaven(Downloader.kt:296)
        at net.mamoe.mirai.console.wrapper.DownloaderKt$downloadMaven$1.invokeSuspend(Downloader.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:238)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:194)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:144)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:57)
        Suppressed: java.lang.IllegalStateException: File not found
                at net.mamoe.mirai.console.wrapper.DownloaderKt.downloadMaven(Downloader.kt:296)
                at net.mamoe.mirai.console.wrapper.DownloaderKt$downloadMaven$1.invokeSuspend(Downloader.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                ... 8 more
        Suppressed: java.lang.IllegalStateException: File not found
                at net.mamoe.mirai.console.wrapper.DownloaderKt.downloadMaven(Downloader.kt:296)
                at net.mamoe.mirai.console.wrapper.DownloaderKt$downloadMaven$1.invokeSuspend(Downloader.kt)
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                ... 8 more
Failed to download newest Protocol lib, please seek for help
```

**Comment by Him188** [comment]
等一等新版本

**Comment by liujiahua123123** [comment]
临时修复版早就更新了 请自己查看

**Comment by kirainmoe** [comment]
"临时修复版"在哪里可以找到？似乎没有什么地方提到过这个东西

**Comment by Him188** [comment]
> "临时修复版"在哪里可以找到？似乎没有什么地方提到过这个东西

[FileRecv.zip](https://github.com/mamoe/mirai-console/files/4384936/FileRecv.zip)
