### ISSUE TITLE
无法解析指令中的图片

### ISSUE THREAD

**Issue by Ulire** [mamoe/mirai-console#183]
在CompositeCommandInternal.kt中也没有发现内建的Image解析器。我的技术水平不够高，也不能排除是操作问题。

java.lang.IllegalStateException: Cannot find a parser for [mirai:image:{8518C54A-AFE4-5367-ED66-833E4048CAB6}.mirai]
	at net.mamoe.mirai.console.internal.command.AbstractReflectionCommand$SubCommandDescriptor.parseArgs(CompositeCommandInternal.kt:167)
	at net.mamoe.mirai.console.internal.command.AbstractReflectionCommand$SubCommandDescriptor.parseAndExecute$mirai_console(CompositeCommandInternal.kt:143)
	at net.mamoe.mirai.console.command.CompositeCommand.onCommand(CompositeCommand.kt:121)
	at net.mamoe.mirai.console.internal.command.ExecuteCommandInternalKt.executeCommandInternal(executeCommandInternal.kt:64)
	at net.mamoe.mirai.console.internal.command.ExecuteCommandInternalKt.executeCommandInternal(executeCommandInternal.kt:61)
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.executeCommand(CommandManagerImpl.kt:184)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt:175)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:123)
	at net.mamoe.mirai.console.pure.ConsoleThreadKt$startupConsoleThread$1.invokeSuspend(ConsoleThread.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Ulire** [comment]
昨晚太晚了有些迷糊，当时想说的是CommandArgumentContext.kt（

**Comment by Him188** [comment]
请临时使用 String 代替

**Comment by Ulire** [comment]
已经用overrideContext自己填上了ImageArgumentParser，只需要删去字符串形式下的前13个字符与最后1个字符就能使用Image类自带的构造方法。
