### ISSUE TITLE
console 正常关闭再启动 AutoSavePluginData 反序列化报错

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai-console#191]
错误日志:
```
2020-09-19 23:30:38 E/xyz.cssxsh.mirai.plugin.pixiv-helper: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'groups' in 'xyz.cssxsh.mirai.plugin.data.PixivHelperPluginData'
...da8abfaeee52adecbe51a68b_16.gif'
                                  ^ at line 21, column 127

net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'groups' in 'xyz.cssxsh.mirai.plugin.data.PixivHelperPluginData'
...da8abfaeee52adecbe51a68b_16.gif'
                                  ^ at line 21, column 127

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:529)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:72)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:41)
	at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:151)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:41)
	at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginData(AbstractJvmPlugin.kt:48)
	at xyz.cssxsh.mirai.plugin.PixivHelperPlugin.onEnable(PixivHelperPlugin.kt:26)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:168)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:192)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:184)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.main(MiraiConsolePureLoader.kt:46)
	at mirai.RunMirai.main(RunMirai.kt:12)
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '1' in 'kotlin.collections.LinkedHashMap'
        profile_image_urls: 
                           ^ at line 20, column 29

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:529)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:112)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:86)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.deserialize(serializerHelper.kt:155)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 19 more
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'auth_info' in 'xyz.cssxsh.mirai.plugin.data.PixivClientData'
        name: cssxsh
                   ^ at line 19, column 21

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeNullableSerializableElement(YamlDecoder.kt:159)
	at xyz.cssxsh.mirai.plugin.data.PixivClientData$$serializer.deserialize(PixivClientData.kt)
	at xyz.cssxsh.mirai.plugin.data.PixivClientData$$serializer.deserialize(PixivClientData.kt:9)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 27 more
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'user' in 'xyz.cssxsh.pixiv.data.AuthResult.AuthInfo'
...  mail_address: cssxsh@gmail.com
                                  ^ at line 18, column 39

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at xyz.cssxsh.pixiv.data.AuthResult$AuthInfo$$serializer.deserialize(AuthResult.kt)
	at xyz.cssxsh.pixiv.data.AuthResult$AuthInfo$$serializer.deserialize(AuthResult.kt:27)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeNullableSerializableElement(YamlDecoder.kt:154)
	... 30 more
Caused by: kotlinx.serialization.MissingFieldException: Field 'name' is required, but it was missing
	at xyz.cssxsh.pixiv.data.AuthResult$User.<init>(AuthResult.kt:54)
	at xyz.cssxsh.pixiv.data.AuthResult$User$$serializer.deserialize(AuthResult.kt)
	at xyz.cssxsh.pixiv.data.AuthResult$User$$serializer.deserialize(AuthResult.kt:44)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 33 more
```

相关类
```
object PixivHelperPluginData : AutoSavePluginData() {
    /**
     * 用于存储用户关联
     */
    private val users: MutableMap<Long, PixivClientData> by value(mutableMapOf())

    /**
     * 用于存储群关联
     */
    private val groups: MutableMap<Long, PixivClientData> by value(mutableMapOf())
.....
```
```
typealias FileUrls = Map<String, String>

@Serializable
data class PixivClientData(
    @SerialName("auth_info")
    val authInfo: AuthResult.AuthInfo? = null,
    @SerialName("config")
    val config: PixivConfig = PixivConfig(proxy = PixivHelperSettings.proxy)
)
    @Serializable
    data class AuthInfo(
        @SerialName("access_token")
        val accessToken: String,
        @SerialName("device_token")
        val deviceToken: String? = "",
        @SerialName("expires_in")
        val expiresIn: Int,
        @SerialName("refresh_token")
        val refreshToken: String,
        @SerialName("scope")
        val scope: String,
        @SerialName("token_type")
        val tokenType: String,
        @SerialName("user")
        val user: User
    )
    @Serializable
    data class User(
        @SerialName("account")
        val account: String,
        @SerialName("id")
        val uid: Long,
        @SerialName("is_mail_authorized")
        val isMailAuthorized: Boolean,
        @SerialName("is_premium")
        val isPremium: Boolean,
        @SerialName("mail_address")
        val mailAddress: String? = null,
        @SerialName("name")
        val name: String,
        @SerialName("profile_image_urls")
        val profileFileUrls: FileUrls,
        @SerialName("x_restrict")
        val xRestrict: Int
    )
```

序列化产生的yml
```
users: 
{}

groups: 
  589573061: 
    auth_info: 
      access_token: aqGhbvNBaCWCHuXS-N-_bBWtuGPTeVQFQyEvv7e-KG4
      device_token: ''
      expires_in: 3600
      refresh_token: dmQyznswcjxsZp4oTTMTluQZNtLtX4HPaWSFGiQrAOY
      scope: ''
      token_type: bearer
      user: 
        account: 2575831437
        id: 12905943
        is_mail_authorized: true
        is_premium: false
        mail_address: cssxsh@gmail.com
        name: cssxsh
        profile_image_urls: 
          px_16x16: 'https://i.pximg.net/user-profile/img/2015/03/27/13/55/11/9148121_0583604eda8abfaeee52adecbe51a68b_16.gif'
          px_50x50: 'https://i.pximg.net/user-profile/img/2015/03/27/13/55/11/9148121_0583604eda8abfaeee52adecbe51a68b_50.gif'
          px_170x170: 'https://i.pximg.net/user-profile/img/2015/03/27/13/55/11/9148121_0583604eda8abfaeee52adecbe51a68b_170.gif'
        x_restrict: 1
    config: 
      client: 
        id: MOBrBDS8blbauoSck0ZfDbtuzpyT
        secret: lsACyCD94FhDUtGTXi3QzcFE2uU1hqtDaKeqrdwj
        hash_secret: 28c1fdd170a5204386cb1313c7077b34f83e4aaf4aa829ce78c231e05b0bae2c
      auth: 
        url: 'https://oauth.secure.pixiv.net/auth/token'
      headers: 
        Accept-Language: zh_CN
        User-Agent: PixivIOSApp/6.0.4 (iOS 9.0.2; iPhone6,1)
        App-OS-Version: 9.0.2
        App-OS: ios
        App-Version: 6.0.4
      proxy: ''
      dns: 'https://1.0.0.1/dns-query'
      ruby_ssl_factory: true
      account: null
      refresh_token: dmQyznswcjxsZp4oTTMTluQZNtLtX4HPaWSFGiQrAOY
```

**Comment by Him188** [comment]
感谢你的提交, 我会尽快修复这个问题

**Comment by Him188** [comment]
在 1.0-RC 添加了备用 JSON 序列化保存方式. YAML 处理失败则会使用 JSON. 
优先使用 YAML 是为了支持注释
