### ISSUE TITLE
注册命令时碰到的几个权限命名空间问题

### ISSUE THREAD

**Issue by CL-Jeremy** [mamoe/mirai-console#197]
> 插件覆盖默认的“/help”？
>
> _Originally posted by @Him188 in https://github.com/mamoe/mirai-console/issues/145#issuecomment-683220041_

1. ~通过注册新的 Command 不能成功覆盖默认的 `/help`~ 已解决，注册时 `register` 函数设置 `override = true`
2. ~无法注册过于复杂的参数（`vararg` 被禁用，也不能将参数设为可选）~ 参考[下方回复](https://github.com/mamoe/mirai-console/issues/197#issuecomment-695844748)
3. (bug) YAML 解析器和本身的权限类均不能解析 `*` 目标：
运行示例代码后，在 console 查询权限出错（期待输出值：插件所注册的 `command.command.help` 命令权限项）
```
> /permission permittedpermissions *
2020-09-20 23:44:36 E/console: net.mamoe.mirai.console.command.description.CommandArgumentParserException: 无法解析 * 为 PermissibleIdentifier
net.mamoe.mirai.console.command.description.CommandArgumentParserException: 无法解析 * 为 PermissibleIdentifier
	at net.mamoe.mirai.console.command.description.PermitteeIdArgumentParser.parse(CommandArgumentParserBuiltins.kt:416)
	at net.mamoe.mirai.console.command.description.PermitteeIdArgumentParser.parse(CommandArgumentParserBuiltins.kt:318)
	at net.mamoe.mirai.console.internal.command.AbstractReflectionCommand$SubCommandDescriptor.parseArgs(CompositeCommandInternal.kt:164)
	at net.mamoe.mirai.console.internal.command.AbstractReflectionCommand$SubCommandDescriptor.parseAndExecute$mirai_console(CompositeCommandInternal.kt:143)
	at net.mamoe.mirai.console.command.CompositeCommand.onCommand(CompositeCommand.kt:121)
	at net.mamoe.mirai.console.internal.command.ExecuteCommandInternalKt.executeCommandInternal(executeCommandInternal.kt:64)
	at net.mamoe.mirai.console.internal.command.ExecuteCommandInternalKt.executeCommandInternal(executeCommandInternal.kt:61)
	at net.mamoe.mirai.console.internal.command.CommandManagerImpl.executeCommand(CommandManagerImpl.kt:184)
	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt:175)
	at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:123)
	at net.mamoe.mirai.console.pure.ConsoleThreadKt$startupConsoleThread$1.invokeSuspend(ConsoleThread.kt:49)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
退出并重新启动 console 后，解析 YAML 出错：
```
Exception in thread "main" net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'grantedPermissionMap' in 'PermissionService'
    - *
      ^ at line 5, column 8

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:529)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:72)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:41)
	at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:151)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:41)
	at net.mamoe.mirai.console.internal.data.builtins.ConsoleBuiltInPluginConfigStorage.load(ConsoleDataScope.kt)
	at net.mamoe.mirai.console.internal.data.builtins.ConsoleDataScope.addAndReloadConfig(ConsoleDataScope.kt:29)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:173)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:184)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon(MiraiConsolePureLoader.kt:150)
	at net.mamoe.mirai.console.pure.MiraiConsolePureLoader.startAsDaemon$default(MiraiConsolePureLoader.kt:149)
	at RunConsoleKt.main(RunConsole.kt:8)
	at RunConsoleKt$$$main.invoke(Unknown Source)
	at kotlin.coroutines.intrinsics.IntrinsicsKt__IntrinsicsJvmKt$createCoroutineUnintercepted$$inlined$createCoroutineFromSuspendFunction$IntrinsicsKt__IntrinsicsJvmKt$1.invokeSuspend(IntrinsicsJvm.kt:205)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.coroutines.ContinuationKt.startCoroutine(Continuation.kt:115)
	at kotlin.coroutines.jvm.internal.RunSuspendKt.runSuspend(RunSuspend.kt:19)
	at RunConsoleKt.main(RunConsole.kt)
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '3' in 'kotlin.collections.LinkedHashMap'
    - *
      ^ at line 5, column 8

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:529)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:112)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:86)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.deserialize(serializerHelper.kt:155)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 18 more
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '0' in 'kotlin.collections.LinkedHashSet'
    - *
      ^ at line 5, column 8

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:529)
	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:81)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 26 more
Caused by: java.lang.IllegalStateException: Cannot deserialize '*' as AbstractPermissibleIdentifier
	at net.mamoe.mirai.console.internal.permission.ParseFromStringImplKt.parseFromStringImpl(parseFromStringImpl.kt:77)
	at net.mamoe.mirai.console.permission.AbstractPermitteeId$Companion.parseFromString(PermitteeId.kt:155)
	at net.mamoe.mirai.console.permission.AbstractPermitteeId$AsStringSerializer$$special$$inlined$map$1.deserialize(serializerHelper.kt:160)
	at net.mamoe.mirai.console.permission.AbstractPermitteeId$AsStringSerializer.deserialize(PermitteeId.kt)
	at net.mamoe.mirai.console.permission.AbstractPermitteeId$AsStringSerializer.deserialize(PermitteeId.kt:162)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 32 more
```
4. ~(bug?) 注册的命令权限前面没有 `plugin.` 命名空间，和父权限不同~ 已解决（另：插件命名空间似乎允许大写字母，但查询父权限时会被转换为小写，也许应该统一一下）

代码在：https://github.com/CL-Jeremy/mirai-console-help-forwarder

~链接：#145 #161~

**Comment by CL-Jeremy** [comment]
注：依赖版本为最新（https://github.com/CL-Jeremy/mirai-console-help-forwarder/commit/74d3324a7f24b9540fe790597e94e033183f637a#diff-392475fdf2bc320d17762ed97109a121R21-R22）

**Comment by CL-Jeremy** [comment]
https://github.com/CL-Jeremy/mirai-console-help-forwarder/commit/4db1eda61dd4cb146b119417c7db3c4f3b3536b4

暂时先这样解决 2. 与 3.，主要问题在 1.（或者说，2. 其实是 by design）。

**Comment by Karlatemp** [comment]
1 是有什么必要吗，如果没有特殊需求请不要和内置命令重名
2 #192

**Comment by CL-Jeremy** [comment]
确实没有什么必要，主要是为了方便兼容过去的插件，而且因为在原 issue 里两次反问是否由插件覆盖内置命令，所以自然认为这样是可行的，毕竟在 1.0 以前这样并没有问题。进一步来说，正如 #161 中的提议，希望可以有办法完全屏蔽从 QQ 端访问 console，至少限制为仅限好友，毕竟群的不可控程度相当高，万一碰到群主、管理员更替（如永封）等意外状况，也许预先提供这样的选项比较妥善。

**Comment by CL-Jeremy** [comment]
发现是自己傻了，注册的时候没有设置 `override = true`
另发现注册的命令权限前面没有 `plugin.` 命名空间，应该是 bug？

**Comment by Him188** [comment]
命名空间目前还有待review，会在1.0-RC稳定

**Comment by Karlatemp** [comment]
3. `*` 权限已在 #206 中于 521f92892660e7f53ec6933d130edeca2169657e 一并修正
4. 已修正于 #202

For mamoe: 未确认权限系统配置序列化是否工作

**Comment by Him188** [comment]
经确认序列化正常
