### ISSUE TITLE
无法正常保存/读取含以非基本类型作key的Map的配置

### ISSUE THREAD

**Issue by 45gfg9** [mamoe/mirai-console#203]
```kotlin
// Config
object GrwWatches : AutoSavePluginConfig("watches") {
    val watches: MutableMap<RepoId, String> by value(HashMap())
}

// Key
@Serializable
data class RepoId(
    val owner: String,
    val name: String
) {
    companion object {
        fun parse(url: String): RepoId // 实现略
    }
    override fun toString(): String = "$owner/$name"
}

// Command
@Handler
suspend fun UserCommandSender.watch(args: String) {
    GrwWatches.watches[RepoId.parse(args)] = args
}
```
以"1/1"和"2/2"调用command

关闭时保存的配置文件
```yml
watches: 
  
    owner: 1
    name: 1: 1/1
  
    owner: 2
    name: 2: 2/2
```

再次开启console时
```
2020-10-07 13:13:28 E/GitHub Release Watcher: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'watches' in 'watches'

 ^ at line 5, column 3

net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for 'watches' in 'watches'

 ^ at line 5, column 3

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:529)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:85)
	at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.deserialize(PluginDataImpl.kt:47)
	at net.mamoe.yamlkt.Yaml.decodeFromString(Yaml.kt:151)
	at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.load(MultiFilePluginDataStorageImpl.kt:40)
	at net.mamoe.mirai.console.plugin.jvm.AbstractJvmPlugin.reloadPluginConfig(AbstractJvmPlugin.kt:56)
	at Watcher.onEnable(Watcher.kt:20)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:100)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
	at net.mamoe.mirai.console.plugin.PluginManager.enable(PluginManager.kt:129)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:169)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:191)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:194)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:49)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:82)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
	at org.itxtech.mcl.Loader.start(Loader.java:127)
	at org.itxtech.mcl.Loader.main(Loader.java:54)
Caused by: net.mamoe.yamlkt.YamlDecodingException: Top-level decoder: deserializing nested class for '0' in 'kotlin.collections.LinkedHashMap'
    name: 1: 1/1
               ^ at line 4, column 17

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:170)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:529)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:101)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:86)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.deserialize(serializerHelper.kt:155)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 46 more
Caused by: net.mamoe.yamlkt.YamlDecodingException: There must be a COLON between class key and value but found STRING for 'RepoId'
    owner: 1
           ^ at line 3, column 13

	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException(ContextualException.kt:154)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlUtils__ContextualExceptionKt.contextualDecodingException$default(ContextualException.kt:128)
	at net.mamoe.yamlkt.internal.YamlUtils.contextualDecodingException$default(Unknown Source)
	at net.mamoe.yamlkt.internal.YamlDecoder$BlockClassDecoder.decodeElementIndex(YamlDecoder.kt:254)
	at RepoId$$serializer.deserialize(RepoId.kt)
	at RepoId$$serializer.deserialize(RepoId.kt:4)
	at net.mamoe.yamlkt.internal.YamlDecoder$AbstractDecoder.decodeSerializableElement(YamlDecoder.kt:168)
	... 54 more
```
同时yml文件重置

能否自定义Map序列化时的行为（使用toString()或其他）（Google kotlin custom serializer无果）

addition: 以json保存配置文件时，文件后缀仍为.yml

**Comment by Him188** [comment]
https://github.com/him188/yamlkt 还未支持复合 key

**Comment by Him188** [comment]
应该先使用 JSON 保存这样的数据

**Comment by Him188** [comment]
YAML语法兼容JSON语法, 因此以 `.yml` 保存没有问题

**Comment by Karlatemp** [comment]
> 应该先使用 JSON 保存这样的数据

JSON是不允许key使用复合key的

**Comment by Him188** [comment]
> > 应该先使用 JSON 保存这样的数据
> 
> JSON是不允许key使用复合key的

Kotlin 序列化的 JSON 是允许的

**Comment by Karlatemp** [comment]
尝试使用
```kotlin
@Serializable(with = Ok.SR::class)
data class Ok(
    val a: String,
    val b: String
) {
    public object SR : KSerializer<Ok> {
        override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("A.W.K.OK", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): Ok =
            decoder.decodeString().split(':').let {
                Ok(it[0], it[1])
            }

        override fun serialize(encoder: Encoder, value: Ok) {
            value.run { encoder.encodeString("$a:$b") }
        }
    }
}
```
