### ISSUE TITLE
1.0-RC-dev-29版本插件不能加载

### ISSUE THREAD

**Issue by nyaoouo** [mamoe/mirai-console#208]
报错：
`Exception in thread "main" net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service net.mamoe.mirai.api.http.HttpApiPluginBase.
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:56)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:38)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$1.invoke(BuiltInJvmPluginLoaderImpl.kt:62)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$1.invoke(BuiltInJvmPluginLoaderImpl.kt:29)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:316)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:742)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:783)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:80)
	at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPlugins(FilePluginLoader.kt:42)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:183)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:127)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:137)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:132)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:194)
	at ny.ny.wsConsole.MainKt.main(Main.kt:15)
Caused by: java.lang.NoSuchMethodError: net.mamoe.mirai.console.plugin.jvm.JvmPluginDescription$Companion.invoke$default(Lnet/mamoe/mirai/console/plugin/jvm/JvmPluginDescription$Companion;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Lkotlin/jvm/functions/Function1;ILjava/lang/Object;)Lnet/mamoe/mirai/console/plugin/jvm/JvmPluginDescription;
	at net.mamoe.mirai.api.http.HttpApiPluginBase.<init>(HttpApiPluginBase.kt:28)
	at net.mamoe.mirai.api.http.HttpApiPluginBase.<clinit>(HttpApiPluginBase.kt:27)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:47)
	... 21 more
`
回滚console 版本到1.0-M4恢复正常

**Comment by Him188** [comment]
并没有release -29的版本，只有-28
