### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 2659494057** [mamoe/mirai-console#210]
Exception in thread "main" java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'
        at net.mamoe.mirai.utils.PlatformLogger$1.<init>(PlatformLogger.jvm.kt)
        at net.mamoe.mirai.utils.PlatformLogger$1.<clinit>(PlatformLogger.jvm.kt)
        at net.mamoe.mirai.utils.PlatformLogger.<init>(PlatformLogger.jvm.kt:55)
        at net.mamoe.mirai.utils.PlatformLogger.<init>(PlatformLogger.jvm.kt)
        at net.mamoe.mirai.utils.SilentLogger.<init>(MiraiLogger.kt:239)
        at net.mamoe.mirai.utils.SilentLogger.<clinit>(MiraiLogger.kt:239)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.<init>(MultiFilePluginDataStorageImpl.kt:29)
        at net.mamoe.mirai.console.data.MultiFilePluginDataStorage$Companion.create(PluginDataStorage.kt:134)
        at net.mamoe.mirai.console.terminal.MiraiConsoleImplementationTerminal.<init>(MiraiConsoleImplementationTerminal.kt:69)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:49)

**Comment by Karlatemp** [comment]
下载的依赖不完整，请检查

**Comment by Him188** [comment]
使用 Kotlin 版本不正确，很有可能是缺少 mirai-core-qqandroid

**Comment by 2659494057** [comment]
> 使用 Kotlin 版本不正确，很有可能是缺少 mirai-core-qqandroid

mirai-core-qqandroid
mirai-console
mirai-console-terminal
这三个均已经放入

**Comment by Him188** [comment]
在不熟悉这些的时候, 请使用 loader
