### ISSUE TITLE
AutoSavePluginData 触发最大间隔时间保存时  程序无响应，CPU占用过高

### ISSUE THREAD

**Issue by cssxsh** [mamoe/mirai-console#211]
使用 jstack 追踪 线程信息，发现  updaterBlock线程 CPU占用过高。
推测是 触发最大间隔时间保存时 updateWhen 锁死
另外 在最小间隔时间保存时没有对currentFirstStartTime清零

"DefaultDispatcher-worker-2" #29 daemon prio=5 os_prio=0 cpu=171171.88ms elapsed=2000.54s tid=0x00000228498e7800 nid=0x1efc runnable  [0x0000004229afe000]
   java.lang.Thread.State: RUNNABLE
	at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1.invokeSuspend(AutoSavePluginData.kt:194)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

   Locked ownable synchronizers:
	- None

"DefaultDispatcher-worker-4" #34 daemon prio=5 os_prio=0 cpu=171343.75ms elapsed=2000.53s tid=0x000002284afae800 nid=0x824 runnable  [0x0000004229ffe000]
   java.lang.Thread.State: RUNNABLE
	at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1.invokeSuspend(AutoSavePluginData.kt:194)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

   Locked ownable synchronizers:
	- None

"DefaultDispatcher-worker-3" #35 daemon prio=5 os_prio=0 cpu=172109.38ms elapsed=2000.53s tid=0x000002284afa9000 nid=0x7e0 runnable  [0x000000422a0fe000]
   java.lang.Thread.State: RUNNABLE
	at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1.invokeSuspend(AutoSavePluginData.kt:194)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by Karlatemp** [comment]
Fixed by https://github.com/mamoe/mirai-console/commit/4564531f8b0300e8227bfc99dff80e6c16e262e8
