### ISSUE TITLE
使用MCL时提示"Could not save AutoLogin in YAML format due to exception in YAML encoder."

### ISSUE THREAD

**Issue by AdorableParker** [mamoe/mirai-console#223]
```
 15:38:58 [INFO] Mirai Console Loader version 1.0.2-a374eff
 15:38:58 [INFO] https://github.com/iTXTech/mirai-console-loader
 15:38:58 [INFO] This program is licensed under GNU AGPL v3
 15:38:58 [DEBUG] Loading script: boot.js
 15:38:58 [DEBUG] Loading script: config.js
 15:38:58 [DEBUG] Loading script: repo.js
 15:38:58 [DEBUG] Loading script: updater.js
 15:38:58 [INFO] Verifying "net.mamoe:mirai-console" version 1.0.0
 15:38:59 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 1.0.0
 15:38:59 [INFO] Verifying "net.mamoe:mirai-core-all" version 1.3.1
2020-11-23 15:39:01 I/main: Starting mirai-console...
2020-11-23 15:39:01 I/main: Backend: version 1.0.0, built on 2020-11-20 11:45:09.
2020-11-23 15:39:01 I/main: Frontend Terminal: version 1.0.0, provided by Mamoe Technologies
2020-11-23 15:39:01 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop
2020-11-23 15:39:01 I/main: 0 plugin(s) enabled.
2020-11-23 15:39:01 I/main: Auto-login 963795439
2020-11-23 15:39:02 I/Bot 963795439: Logging in...
2020-11-23 15:39:08 I/Bot 963795439: Login successful
2020-11-23 15:39:08 I/main: mirai-console started successfully.
2020-11-23 15:40:01 W/main: Could not save AutoLogin in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.ListLikeSerializer.serialize(CollectionSerializers.kt:67)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invokeSuspend(AutoSavePluginData.kt:116)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invoke(AutoSavePluginData.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1.invokeSuspend(AutoSavePluginData.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 15:40:01 W/main: Could not save Logger in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invokeSuspend(AutoSavePluginData.kt:116)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invoke(AutoSavePluginData.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1.invokeSuspend(AutoSavePluginData.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 15:40:01 W/main: Could not save ExtensionSelector in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invokeSuspend(AutoSavePluginData.kt:116)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invoke(AutoSavePluginData.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1.invokeSuspend(AutoSavePluginData.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

2020-11-23 15:40:01 W/main: Could not save PermissionService in YAML format due to exception in YAML encoder. Please report this exception and relevant configurations to https://github.com/mamoe/mirai-console/issues/new
java.lang.AbstractMethodError: Receiver class net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder does not define or inherit an implementation of the resolved method 'abstract kotlinx.serialization.encoding.CompositeEncoder beginCollection(kotlinx.serialization.descriptors.SerialDescriptor, int, kotlinx.serialization.KSerializer[])' of interface kotlinx.serialization.encoding.Encoder.
        at kotlinx.serialization.encoding.Encoder$DefaultImpls.beginCollection(Encoding.kt:257)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.beginCollection(YamlEncoder.kt:479)
        at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:119)
        at net.mamoe.mirai.console.data.SerializableValue$Companion$serializableValueWith$$inlined$map$1.serialize(serializerHelper.kt:158)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement0(YamlEncoder.kt:460)
        at net.mamoe.yamlkt.internal.YamlEncoder$BlockMapOrClassEncoder.encodeSerializableElement0(YamlEncoder.kt:329)
        at net.mamoe.yamlkt.internal.YamlEncoder$AbstractEncoder.encodeSerializableElement(YamlEncoder.kt:467)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:105)
        at net.mamoe.mirai.console.internal.data.PluginDataImpl$updaterSerializer$1.serialize(PluginDataImpl.kt:47)
        at net.mamoe.yamlkt.Yaml.encodeToString(Yaml.kt:108)
        at net.mamoe.mirai.console.internal.data.MultiFilePluginDataStorageImpl.store(MultiFilePluginDataStorageImpl.kt:76)
        at net.mamoe.mirai.console.data.AutoSavePluginData.doSave(AutoSavePluginData.kt:144)
        at net.mamoe.mirai.console.data.AutoSavePluginData.access$doSave(AutoSavePluginData.kt:31)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invokeSuspend(AutoSavePluginData.kt:116)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1$4.invoke(AutoSavePluginData.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:160)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at net.mamoe.mirai.console.data.AutoSavePluginData$updaterBlock$1.invokeSuspend(AutoSavePluginData.kt:115)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

>
```

**Comment by Him188** [comment]
需要 mirai-core 1.3.3

**Comment by AdorableParker** [comment]
![image](https://user-images.githubusercontent.com/35246761/99939351-d36db180-2da4-11eb-8a88-a844e08dd4af.png)
emmmm
