### ISSUE TITLE
使用plugin.yml配置依赖信息时依赖的版本号被解析为空字符串

### ISSUE THREAD

**Issue by CHH2000day** [mamoe/mirai-console#224]
环境信息:
mirai-core:1.3.3
mirai-console:1.0.0

使用plugin.yml配置插件的依赖后加载插件时报java.lang.IllegalArgumentException: Syntax error:.

用mirai-console的源代码打断点后发现插件所对应的PluginDependency.versionRequirement被解析为空字符串而非null
plugin.yml配置的依赖如图:
![image](https://user-images.githubusercontent.com/14977308/99982952-3469a980-2de6-11eb-83b2-439aae77a813.png)
如果使用dependsOn引入这一依赖则不会发生异常

日志如下:
2020-11-23 23:33:20 E/main: Failed to init MiraiConsole.
java.lang.IllegalArgumentException: Syntax error:
        at net.mamoe.mirai.console.util.SemVersion$Requirement.<init>(SemVersion.kt:102)
        at net.mamoe.mirai.console.util.SemVersion$Companion.parseRangeRequirement(SemVersion.kt:192)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImplKt.checkSatisfies(PluginManagerImpl.kt:252)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl$sortByDependencies$1.invoke(PluginManagerImpl.kt:196)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl$sortByDependencies$2.invoke(PluginManagerImpl.kt:202)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl$sortByDependencies$4.invoke(PluginManagerImpl.kt:214)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl$sortByDependencies$4.invoke(PluginManagerImpl.kt:222)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.sortByDependencies(PluginManagerImpl.kt:225)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:184)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:127)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:137)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:155)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:201)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
Caused by: java.lang.IllegalArgumentException: Invalid requirement: Empty requirement rule.
        at net.mamoe.mirai.console.internal.util.semver.SemVersionInternal.parseRangeRequirement(SemVersionInternal.kt:171)
        at net.mamoe.mirai.console.util.SemVersion$Requirement.<init>(SemVersion.kt:100)
        ... 15 more

**Comment by Karlatemp** [comment]
请问 `-com`.... `-` 和 `com` 连一起是认真的吗

**Comment by CHH2000day** [comment]
> 请问 `-com`.... `-` 和 `com` 连一起是认真的吗

截的时候手残吧空格删了...不过加不加不影响重现

**Comment by Him188** [comment]
已修复, 在 `1.0.1` 发布前请尝试版本 `1.0.1-dev-1`
