### ISSUE TITLE
在Centos8.2系统运行Mirai-console报错Bad file descriptor

### ISSUE THREAD

**Issue by licaoshun** [mamoe/mirai-console#229]
当我运行命令`./mcl`时，`mirai-console`正常启动，没有任何问题。

但当我尝试运行命令`nohup ./mcl >output 2>&1 &`时，虽然机器人能接收、处理和发送消息，但此时CPU和`output`文件开始持续爆涨，不停止。以下是来自`output`文件中的信息。
``` java
2020-11-29 00:19:26 E/console: Unhandled exception
java.io.IOError: java.io.IOException: Bad file descriptor
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:913)
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:946)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:637)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
	at net.mamoe.mirai.console.terminal.ConsoleInputImpl$requestInput$$inlined$suspendCancellableCoroutine$lambda$1.run(ConsoleInputImpl.kt:46)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: Bad file descriptor
	at java.base/java.io.FileInputStream.read0(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:223)
	at org.jline.utils.NonBlockingInputStreamImpl.run(NonBlockingInputStreamImpl.java:216)
	... 1 more
```
`output`文件中的内容一直重复上面的错误。
我尝试删除plugins文件夹中所有的jar包，此问题依然没有解决，因此我猜想这个错误可能来自`mirai-console`。
请问我该如何解决它？

**Comment by Karlatemp** [comment]
mcl 有个参数可以设置terminal启动参数，请使用 ./mcl --help查看是哪个参数并添加--no-console到该启动参数设置临时解决问题

**Comment by duanluan** [comment]
> 当我运行命令 `./mcl` 时，`mirai-console` 正常启动，没有任何问题。
> 
> 但当我尝试运行命令 `nohup ./mcl >output 2>&1 &` 时，虽然机器人能接收、处理和发送消息，但此时 CPU 和 `output` 文件开始持续爆涨，不停止。以下是来自 `output` 文件中的信息。
> 
> ```java
> 2020-11-29 00:19:26 E/console: Unhandled exception
> java.io.IOError: java.io.IOException: Bad file descriptor
> 	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
> 	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
> 	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
> 	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:913)
> 	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:946)
> 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:637)
> 	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:454)
> 	at net.mamoe.mirai.console.terminal.ConsoleInputImpl$requestInput$$inlined$suspendCancellableCoroutine$lambda$1.run(ConsoleInputImpl.kt:46)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
> 	at java.base/java.lang.Thread.run(Thread.java:832)
> Caused by: java.io.IOException: Bad file descriptor
> 	at java.base/java.io.FileInputStream.read0(Native Method)
> 	at java.base/java.io.FileInputStream.read(FileInputStream.java:223)
> 	at org.jline.utils.NonBlockingInputStreamImpl.run(NonBlockingInputStreamImpl.java:216)
> 	... 1 more
> ```
> 
> `output` 文件中的内容一直重复上面的错误。 我尝试删除 plugins 文件夹中所有的 jar 包，此问题依然没有解决，因此我猜想这个错误可能来自 `mirai-console`。 请问我该如何解决它？

不用管这个错误。
nohup ./mcl > /dev/null &
