### ISSUE TITLE
[Android] java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/MemoryUsage;

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai-console#250]
在安卓系统上运行
MiraiConsoleTerminalLoader.startAsDaemon
时，提示找不到MemoryUsage类，似乎这个api并没有在安卓系统里被提供

系统：安卓9

**Comment by zhaodice** [comment]
I/System.out: 2020-02-21 22:18:06 I/main: Starting mirai-console...
I/System.out: 2020-02-21 22:18:06 I/main: Backend: version 2.0-M1-1, built on 2020-12-19 23:26:13.
I/System.out: 2020-02-21 22:18:06 I/main: Frontend Terminal: version 2.0-M1-1, provided by Mamoe Technologies
I/System.out: 2020-02-21 22:18:07 I/Net 3403310837: Login successful
I/System.out: 2020-02-21 22:18:07 E/main: Failed to init MiraiConsole.
    java.lang.IllegalStateException: Failed to init command net.mamoe.mirai.console.command.BuiltInCommands$StatusCommand@9cb484f.
        at net.mamoe.mirai.console.internal.command.CommandManagerImpl.registerCommand(CommandManagerImpl.kt:83)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(Unknown Source:7)
        at net.mamoe.mirai.console.command.BuiltInCommands.registerAll$mirai_console(BuiltInCommands.kt:524)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:196)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:150)
        at org.mirai.zhao.dice.console.ConsoleService$startConsole$1.run(ConsoleService.kt:110)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/MemoryUsage;
        at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
        at java.lang.reflect.Method.getParameterTypes(Method.java:186)
        at java.lang.Class.getDeclaredMethods(Class.java:1881)
...

**Comment by zhaodice** [comment]
换成2.0-M2后

I/System.out: 2020-02-21 22:27:34 I/main: Starting mirai-console...
I/System.out: 2020-02-21 22:27:34 I/main: Backend: version 2.0-M2, built on 2020-12-28 18:39:29.
I/System.out: 2020-02-21 22:27:34 I/main: Frontend Terminal: version 2.0-M2, provided by Mamoe Technologies
I/System.out: 2020-02-21 22:27:35 I/Net 3403310837: Login successful
I/System.out: 2020-02-21 22:27:35 E/main: Failed to init MiraiConsole.
    java.lang.IllegalStateException: Failed to init command net.mamoe.mirai.console.command.BuiltInCommands$StatusCommand@1ba44e5.
        at net.mamoe.mirai.console.internal.command.CommandManagerImpl.registerCommand(CommandManagerImpl.kt:83)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.registerCommand(Unknown Source:7)
        at net.mamoe.mirai.console.command.BuiltInCommands.registerAll$mirai_console(BuiltInCommands.kt:524)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:196)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:151)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:150)
        at org.mirai.zhao.dice.console.ConsoleService$startConsole$1.run(ConsoleService.kt:110)
        at java.lang.Thread.run(Thread.java:764)
    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/MemoryUsage;
        at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
        at java.lang.reflect.Method.getParameterTypes(Method.java:186)
        at java.lang.Class.getDeclaredMethods(Class.java:1881)

**Comment by zhaodice** [comment]
这里提供一个判断是否是安卓系统的代码：

public class JVMDetector {
    final static public boolean isAndroid = "Dalvik".equals(System.getProperty("java.vm.name"));
}

**Comment by Karlatemp** [comment]
console `2.0-RC` 已经进行了处理
