### ISSUE TITLE
载入插件报错 Caused by: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by zhaodice** [mamoe/mirai-console#258]
安卓无法运行：
net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service zhao.dice.plugin.MiraiPluginLoader.
...
I/System.out: Caused by: java.lang.ClassNotFoundException: zhao.dice.plugin.MiraiPluginLoader
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:48)
    	... 24 more
    Caused by: java.lang.ClassNotFoundException: zhao.dice.plugin.MiraiPluginLoader
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass$mirai_console(JvmPluginClassLoader.kt:110)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader.findClass(JvmPluginClassLoader.kt:51)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	... 27 more
I/System.out: 2021-01-11 10:06:48 I/Bot 3403310837: Bot cancelled: Job was cancelled
I/System.out: 2021-01-11 10:06:48 E/Bot 3403310837: An exception was thrown under a coroutine of Bot
    kotlinx.coroutines.JobCancellationException: Job was cancelled; job=SupervisorJobImpl{Cancelled}@f0f449d

但是这个类是确实存在的，另外反编译该jar(dex)也确认已经将类打包了进去
相关文件：
package zhao.dice.plugin
object MiraiPluginLoader : KotlinPlugin(
        JvmPluginDescription(
        id = "zhao.dice",
        version = "1.0.0", ) {
            name("ZhaoDice")
            author("赵怡然")
            }
){
...
运行环境：安卓11
复现过程：使用d8编译器，将插件编译成dex形式的jar放入安卓后就会出现”java.lang.ClassNotFoundException“异常，而且这个插件在Windows上运行正常

在PC上运行正常：
2021-01-11 18:21:44 I/main: 1 plugin(s) enabled.
2021-01-11 18:21:44 I/main: mirai-console started successfully.

**Comment by zhaodice** [comment]
注：安卓x86 模拟器环境

**Comment by zhaodice** [comment]
相关资料：https://www.jianshu.com/p/a620e368389a

URLClassLoader
【只能用于加载jar文件，但是由于 dalvik 不能直接识别jar，所以在 Android 中无法使用这个加载器。】

而net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoader 却使用了 URLClassLoader
可能是问题的原因。

**Comment by zhaodice** [comment]
相关资料2：https://blog.csdn.net/cylzll/article/details/79498328
1、Android中有哪几种ClassLoader？它们的作用和区别是什么？

ClassLoader是个抽象类，其具体实现的子类有 BaseDexClassLoader 和SecureClassLoader 。
SecureClassLoader 的子类是 URLClassLoader ，其只能用来加载 jar 文件，【这在 Android 的 Dalvik/ART 上没法使用的。】

**Comment by zhaodice** [comment]
因此，可能将URLClassLoader换掉，改成安卓支持的ClassLoader应该就正常了。

**Comment by ceneax** [comment]
请问怎么编译插件，  我用idea直接生成jar，放入plugin文件夹，不能加载，  估计编译方式不正确，你是怎么编译的

**Comment by ceneax** [comment]
我是linux上的，不是安卓手机上用的

**Comment by Karlatemp** [comment]
在安卓环境下应该由前端自行实现插件载入器

**Comment by zhaodice** [comment]
> 请问怎么编译插件， 我用idea直接生成jar，放入plugin文件夹，不能加载， 估计编译方式不正确，你是怎么编译的

你参照一下MiraiNative这个项目，下载release他的jar，jar里面有个META-INF文件夹，然后有个services文件夹，最关键是里面的文件，老长了什么Jvm什么的，把文件内容改成你的插件入口点，放入你的jar包对应相同位置就行了。

**Comment by zhaodice** [comment]
> 在安卓环境下应该由前端自行实现插件载入器

竟然插件载入器可以自己实现啊，有相关文档吗，我好像没见过

**Comment by zhaodice** [comment]
我仿照一下看看能不能自己实现一个

**Comment by Him188** [comment]
在 MiraiConsoleImplementation 里可以提供 builtInPluginLoaders

**Comment by zhaodice** [comment]
@Him188 我又测试了一下，发现把mirai-console里的JvmPluginClassLoader里的
URLClassLoader(arrayOf(file.toURI().toURL()), parent)
改成
BaseDexClassLoader(file.absolutePath,file.parentFile,null, parent)
就可以在安卓上正常调用插件了，所以可以先判断一下是否是dalvik虚拟机，然后选择性调用？

**Comment by zhaodice** [comment]
dalvik用
internal class JvmPluginClassLoader(
    val file: File,
    parent: ClassLoader?,
    val classLoaders: Collection<JvmPluginClassLoader>,
) : BaseDexClassLoader(file.absolutePath,file.parentFile,null, parent) {

jvm用
internal class JvmPluginClassLoader(
    val file: File,
    parent: ClassLoader?,
    val classLoaders: Collection<JvmPluginClassLoader>,
) : URLClassLoader(arrayOf(file.toURI().toURL()), parent) {

**Comment by Him188** [comment]
mirai-console 没有 android 依赖, 请自行实现

**Comment by zhaodice** [comment]
> 
> 
> mirai-console 没有 android 依赖, 请自行实现

可以自行添加
//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//
package dalvik.system

import java.io.File
import java.net.URL
import java.util.*

public open class BaseDexClassLoader(dexPath: String, optimizedDirectory: File, librarySearchPath: String?, parent: ClassLoader?) : ClassLoader() {
    @Throws(ClassNotFoundException::class)
    override fun findClass(name: String): Class<*> {
        throw RuntimeException("Stub!")
    }

    override fun findResource(name: String): URL {
        throw RuntimeException("Stub!")
    }

    override fun findResources(name: String): Enumeration<URL> {
        throw RuntimeException("Stub!")
    }

    public override fun findLibrary(name: String): String {
        throw RuntimeException("Stub!")
    }

    @Synchronized
    override fun getPackage(name: String): Package {
        throw RuntimeException("Stub!")
    }

    override fun toString(): String {
        throw RuntimeException("Stub!")
    }

    init {
        throw RuntimeException("Stub!")
    }
}

这些都是Stub，安卓内部已经实现了，你只需要加上这个作为接口即可。
