### ISSUE TITLE
Graphical not working on macOS

### ISSUE THREAD

**Issue by 45gfg9** [mamoe/mirai-console#28]
OS: macOS 10.15.4
Core: 0.32.0
Graphical: 0.0.5
When using Java 8, window did not pop up and gave following output in terminal:
```
Version check complete, starting Mirai
shadow-Protocol:/Users/45gfg9/Downloads/mirai/content/mirai-core-qqandroid-jvm-0.32.0.jar
Console        :/Users/45gfg9/Downloads/mirai/content/mirai-console-graphical-0.0.5.jar
Root           :/Users/45gfg9/Downloads/mirai/
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.mamoe.mirai.console.wrapper.WrapperMain.start(WrapperMain.kt:156)
	at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative(WrapperMain.kt:133)
	at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:89)
Caused by: java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.mamoe.mirai.console.graphical.MiraiConsoleGraphicalLoader$Companion.load(MiraiConsoleGraphicalLoader.kt:36)
	at net.mamoe.mirai.console.graphical.MiraiConsoleGraphicalLoader.load(MiraiConsoleGraphicalLoader.kt)
	... 7 more
```
Yes, it's problem with Java version being too low (`Caused by: java.lang.UnsupportedClassVersionError: javafx/application/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

When using Java 13 / 14, window does pop up, but with NPE trace:
<img width="657" alt="截屏2020-04-04 21 02 23" src="https://user-images.githubusercontent.com/37043529/78451328-963e9d00-76b7-11ea-9eca-f4e642ca949c.png">
```
java.lang.NullPointerException
	at com.jfoenix.skins.JFXTextFieldSkin.updateTextPos(JFXTextFieldSkin.java:109)
	at com.jfoenix.skins.JFXTextFieldSkin.layoutChildren(JFXTextFieldSkin.java:93)
	at javafx.scene.control.Control.layoutChildren(Control.java:601)
	at javafx.scene.Parent.layout(Parent.java:1206)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Parent.layout(Parent.java:1213)
	at javafx.scene.Scene.doLayoutPass(Scene.java:576)
	at javafx.scene.Scene.preferredSize(Scene.java:1748)
	at javafx.scene.Scene$2.preferredSize(Scene.java:393)
	at com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.stage.Window$12.invalidated(Window.java:1086)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.stage.Window.setShowing(Window.java:1174)
	at javafx.stage.Window.show(Window.java:1189)
	at javafx.stage.Stage.show(Stage.java:273)
	at tornadofx.App.start(App.kt:101)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by liujiahua123123** [comment]
可以用那个mac_os的一键包(.dmg), 在release
Graphical的环境问题一经发现并正在下个热更新中更改


Please use the installer attached in the release page for macOS, but knowing that Graphical is designed for users, not devs. if you want to develop on plugins, etc, Console-Pure would be a better choice.

The version issue of Console-graphical has been addressed, which would be solved in next release(a hot update)
