### ISSUE TITLE
请问如何打包有springboot的插件

### ISSUE THREAD

**Issue by lc6a** [mamoe/mirai-console#291]
我尝试将一个spring项目打包成mirai-console插件，在test里面通过Terminal前端启动运行都是可以的（spring日志不知道被重定向到哪里去了，不过问题不大，回复消息是正常的）。
当使用gradle插件buildPlugin打包后，启动mcl有以下报错：
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::

2021-02-14 22:02:29 E/SpringMiraiDemoPlugin: java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
java.lang.IllegalArgumentException: No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
        at org.springframework.util.Assert.notEmpty(Assert.java:470)
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getCandidateConfigurations(AutoConfigurationImportSelector.java:180)
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector.getAutoConfigurationEntry(AutoConfigurationImportSelector.java:123)
        at org.springframework.boot.autoconfigure.AutoConfigurationImportSelector$AutoConfigurationGroup.process(AutoConfigurationImportSelector.java:434)
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGrouping.getImports(ConfigurationClassParser.java:879)
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809)
        at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780)
        at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:336)
        at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:252)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:285)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:99)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:751)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:569)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
        at com.lc.spring_mirai.SpringMiraiDemoPlugin.onEnable(SpringMiraiDemoPlugin.kt:28)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:113)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:119)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:36)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:129)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:172)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:202)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
        at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
        at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
        at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
        at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
        at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
        at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
        at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
        at org.mozilla.javascript.Context.call(Context.java:554)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
        at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
        at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
        at com.sun.proxy.$Proxy4.run(Unknown Source)
        at org.itxtech.mcl.script.ScriptManager.phaseBoot(ScriptManager.java:101)
        at org.itxtech.mcl.Loader.start(Loader.java:129)
        at org.itxtech.mcl.Loader.main(Loader.java:53)
        2021-02-14 22:02:29 I/main: 2 plugin(s) enabled.（这里说明插件onLoad调用成功了，但是Spring启动报错了，因此本插件功能都无法使用）
```
插件项目的地址：[spring_mirai](https://github.com/lc6a/spring_mirai)

其中test前端启动代码段：
```kotlin
        MiraiConsoleTerminalLoader.startAsDaemon()
        runBlocking {
            val bot = BotFactory.newBot(qq, password) {
                fileBasedDeviceInfo()
                protocol = BotConfiguration.MiraiProtocol.ANDROID_PAD
            }.alsoLogin()
            SpringMiraiDemoPlugin.load()
            SpringMiraiDemoPlugin.enable()
            bot.join()
        }
```

插件定义代码段：
```kotlin
object SpringMiraiDemoPlugin: KotlinPlugin(
    JvmPluginDescription(
        id = "com.lc.spring.mirai.SpringMiraiDemoPlugin",
        version = "0.0.1",
        name = "SpringMiraiDemoPlugin"
    )
) {
    override fun onEnable() {
        logger.debug { "Start Spring Mirai" }
        runApplication<SpringMiraiApplication>()
    }
}
```

[插件jar文件](https://github.com/lc6a/spring_mirai/blob/2.0/build/mirai/spring_mirai-2.3.2-dev2.mirai.jar)

**Comment by Karlatemp** [comment]
我认为你应该与阅读 `org.springframework.boot.autoconfigure.AutoConfigurationImportSelector` 的源码

**Comment by lc6a** [comment]
> 我认为你应该去阅读 `org.springframework.boot.autoconfigure.AutoConfigurationImportSelector` 的源码

谢谢，但我仍然没有弄清楚如何解决此问题，恳请各位提供帮助，以下是我的一些想法：
1. 原报错是spring.factories文件里面缺少一些东西，通过对比mirai构建的jar包和spring构建的jar包，我发现mirai打包可能无法让各模块中META-INF同名文件共存。以META-INF/spring.factories文件为例，我的插件本身以及不少第三方库都有该文件，使用spring打包时，各依赖都是以jar包套jar包的形式存在，因此项目本身的文件与依赖库的同名文件都能够在jar包中存在，而如果使用mirai打包，只有插件本身的META-INF/spring.factories文件，其他依赖库的该文件都没有，这应该是插件启动springboot报错的直接原因。
2. spring打包后的主类并非是我自己的main所在类，而是spring的JarLoader，我尝试反射通过该类作为插件onEnable内容无果，我想应该没必要这样做。
3. `AutoConfigurationImportSelector`类应该和`@Import`注解、`@EnableAutoConfiguration`有关，我对这些还不太了解，但该类似乎无法解决想法1中依赖库的META-INF/spring.factories文件缺失的问题。

**Comment by Karlatemp** [comment]
你可以尝试以下几种方法
1. 另外开一个插件项目专门加载 Spring 打包出来的 jar，这应该是最简单的方法
2. 写个方法读取各个库的 `META-INF/spring.factories`, 然后根据一定的规则组合到一起, 写入 `项目/src/main/resources/META-INF/spring.factories`. `shadowJar` 一直都无法自动处理这种同名文件, 这个比较复杂, 并且可能还有其他的冲突同名文件
