### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by liaosunny123** [mamoe/mirai-console#298]
[92m2021-02-21 20:35:55 I/stdout: [2021-02-21 20:35:55 MxLib Selenium - Chrome] Or disable it with `-Dmxlib.selenium.chrome.no-mirror`[0m[mLogin failed: Unexpected JSON token at offset 11: Expected '[, kind: LIST'JSON input: {"display":"MIRAI.434413.001","product":".....[m[31m2021-02-21 20:35:55 E/console: java.lang.reflect.InvocationTargetExceptionjava.lang.reflect.InvocationTargetException	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.base/java.lang.reflect.Method.invoke(Unknown Source)	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:130)	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 11: Expected '[, kind: LIST'JSON input: {"display":"MIRAI.434413.001","product":".....	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)	at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:333)	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:39)	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)	at kotlinx.serialization.internal.PrimitiveArraySerializer.deserialize(CollectionSerializers.kt:179)	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt)	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt:21)	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)	at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt:78)	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:227)	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt)	at net.mamoe.mirai.internal.QQAndroidBot.initClient(QQAndroidBot.kt:71)	at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:64)	at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:34)	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:192)	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:126)	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:170)	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle$default(BuiltInCommands.kt:167)	... 22 more[0m[m>

**Comment by Karlatemp** [comment]
删除设备文件

**Comment by liaosunny123** [comment]
根目录下的device.json吗，删除过了的

**Comment by Karlatemp** [comment]
`bots\<id>\device.json`

**Comment by liaosunny123** [comment]
删除了，继续报错
Login failed: Unexpected JSON token at offset 11: Expected '[, kind: LIST'JSON input: {"display":"MIRAI.085512.001","product":".....[m[31m2021-02-21 22:58:00 E/console: java.lang.reflect.InvocationTargetExceptionjava.lang.reflect.InvocationTargetException	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)	at java.base/java.lang.reflect.Method.invoke(Unknown Source)	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Static.call(CallerImpl.kt:106)	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:173)	at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:73)	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:283)	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:88)	at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)	at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:161)	at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:130)	at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)	at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:183)	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 11: Expected '[, kind: LIST'JSON input: {"display":"MIRAI.085512.001","product":".....	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)	at kotlinx.serialization.json.internal.JsonReader.fail(JsonReader.kt:333)	at kotlinx.serialization.json.internal.StreamingJsonDecoder.beginStructure(StreamingJsonDecoder.kt:39)	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:29)	at kotlinx.serialization.internal.PrimitiveArraySerializer.deserialize(CollectionSerializers.kt:179)	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:41)	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:63)	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt)	at net.mamoe.mirai.utils.DeviceInfo$$serializer.deserialize(DeviceInfo.kt:21)	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:63)	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:33)	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)	at net.mamoe.mirai.utils.DeviceInfo$Companion.from(DeviceInfo.kt:78)	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt:227)	at net.mamoe.mirai.utils.LoginSolverKt$getFileBasedDeviceInfoSupplier$1.invoke(LoginSolver.kt)	at net.mamoe.mirai.internal.QQAndroidBot.initClient(QQAndroidBot.kt:71)	at net.mamoe.mirai.internal.QQAndroidBot.<init>(QQAndroidBot.kt:64)	at net.mamoe.mirai.internal.BotFactoryImpl.newBot(BotFactory.kt:34)	at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:115)	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBotImpl(MiraiConsole.kt:192)	at net.mamoe.mirai.console.MiraiConsole$INSTANCE.addBot(MiraiConsole.kt:126)	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle(BuiltInCommands.kt:170)	at net.mamoe.mirai.console.command.BuiltInCommands$LoginCommand.handle$default(BuiltInCommands.kt:167)	... 22 more[0m[m>

**Comment by liaosunny123** [comment]
疑似是console自己在修改json，两次错误不一样

**Comment by Karlatemp** [comment]
请提供版本号和插件列表

**Comment by liaosunny123** [comment]
版本号:2.4.0(mirai三件套)
插件列表:适配于2.4.0的native和最新release的httpapi

**Comment by Karlatemp** [comment]
确认全部 `device.json` 已经删除?

**Comment by liaosunny123** [comment]
确定。
看两个日志可以发现两个日志内容是不同的，报错的地方，也就是应该是重新生成的

**Comment by Him188** [comment]
@liaosunny123 请问是以下哪种情况:
1. 第一次登录, 版本 2.4.0
2. 非第一次登录, 版本一直用的是 2.4.0
3. 非第一次登录, 版本以前低于 2.3.0, 现在更新到 2.4.0

**Comment by liaosunny123** [comment]
1，以前用过2.3.0版本，也是登录不了

**Comment by liaosunny123** [comment]
[92m2021-02-17 20:52:49 I/main: Starting mirai-console...[0m[m
[92m2021-02-17 20:52:49 I/main: Backend: version 2.3.0, built on 2021-02-03 13:23:42.[0m[m
[92m2021-02-17 20:52:49 I/main: Frontend Terminal: version 2.3.0, provided by Mamoe Technologies[0m[m

[31m2021-02-17 20:52:49 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.internal.util.ServiceLoadException: Could not load service com.ssttkkl.mirai.bangumiplugin.MiraiBangumiPlugin.
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:57)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadAllServices(PluginServiceHelper.kt:39)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$2.invoke(BuiltInJvmPluginLoaderImpl.kt:75)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl$extractPlugins$1$2.invoke(BuiltInJvmPluginLoaderImpl.kt:29)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:314)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.FlatteningSequence$iterator$1.ensureItemIterator(Sequences.kt:307)
	at kotlin.sequences.FlatteningSequence$iterator$1.hasNext(Sequences.kt:303)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:752)
	at kotlin.sequences.SequencesKt___SequencesKt.toSet(_Sequences.kt:793)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.extractPlugins(BuiltInJvmPluginLoaderImpl.kt:94)
	at net.mamoe.mirai.console.plugin.loader.AbstractFilePluginLoader.listPlugins(FilePluginLoader.kt:51)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.listPlugins(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.listAndSortAllPlugins(PluginManagerImpl.kt:186)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.findAndSortAllPluginsUsingBuiltInLoaders(PluginManagerImpl.kt:130)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:140)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:152)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:209)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:153)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:152)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:48)
Caused by: java.lang.NoSuchMethodError: 'net.mamoe.mirai.console.plugin.jvm.JvmPluginDescription net.mamoe.mirai.console.plugin.jvm.JvmPluginDescription$Companion.invoke$default(net.mamoe.mirai.console.plugin.jvm.JvmPluginDescription$Companion, java.lang.String, java.lang.String, java.lang.String, kotlin.jvm.functions.Function1, int, java.lang.Object)'
	at com.ssttkkl.mirai.bangumiplugin.MiraiBangumiPlugin.<init>(MiraiBangumiPlugin.kt:29)
	at com.ssttkkl.mirai.bangumiplugin.MiraiBangumiPlugin.<clinit>(MiraiBangumiPlugin.kt:25)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at net.mamoe.mirai.console.internal.util.PluginServiceHelper.loadService(PluginServiceHelper.kt:48)
	... 23 more
[0m[m

**Comment by liaosunny123** [comment]
以前的报错如上

**Comment by Him188** [comment]
请尝试删除整个bots目录和根目录的device.json

**Comment by liaosunny123** [comment]
好的，我尝试进行。顺便再重新安装一遍。不过可能没有很大作用，之前也是分别删除过device.json和bot了的

**Comment by Him188** [comment]
@liaosunny123 请问测试结果如何

**Comment by liaosunny123** [comment]
目前正常，以后有问题重开issue。
疑似复现几率极小，只有原先电脑这样
