### ISSUE TITLE
安装了mirai-login-solver-selenium后，运行mirai_console报错 

### ISSUE THREAD

**Issue by Wushengyao** [mamoe/mirai-console#299]
在安装mirai-login-solver-selenium之前运行正常，但是由于登录QQ需要验证码，所以按照指示安装了验证码插件mirai-login-solver-selenium。此后运行mirai_console会报如下错误：  
  
"D:\Program Files\Java\jdk-14.0.2\bin\java.exe" -Dfile.encoding=GBK -jar 
 C:\Users\wushengyao\Desktop\Tutorial\提交版v0.2\QQBot\mcl.jar
 20:00:45 [INFO] iTXTech Mirai Console Loader version 1.0.5-9b6cf6d
 20:00:45 [INFO] https://github.com/iTXTech/mirai-console-loader
 20:00:45 [INFO] This program is licensed under GNU AGPL v3
 20:00:45 [DEBUG] Loading script: announcement.js
 20:00:46 [DEBUG] Loading script: boot.js
 20:00:46 [DEBUG] Loading script: config.js
 20:00:46 [DEBUG] Loading script: oraclejdk.js
 20:00:46 [INFO] OracleJDK is detected. MCL will download BouncyCastle automatically.
 20:00:46 [DEBUG] Loading script: repo.js
 20:00:46 [DEBUG] Loading script: updater.js
 20:00:46 [INFO] Fetching Mirai Console Loader Announcement...
 20:00:47 [INFO] Mirai Console Loader Announcement:
Mirai Console Loader 公告栏

 20:00:47 [INFO] Verifying "org.bouncycastle:bcprov-jdk15on" version 1.64
 20:00:47 [INFO] Verifying "net.mamoe:mirai-console" version 2.4.0
 20:00:47 [INFO] Verifying "net.mamoe:mirai-console-terminal" version 2.4.0
 20:00:47 [INFO] Verifying "net.mamoe:mirai-core-all" version 2.4.0
 20:00:47 [INFO] Verifying "net.mamoemirai-login-solver-selenium" version 
 20:00:47 [ERROR] org.mozilla.javascript.WrappedException: Wrapped java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1 (updater.js#45)
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692)
	at script.checkLocalFile(updater.js:45)
	at script.check(updater.js:53)
	at script(updater.js:38)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.ArrowFunction.call(ArrowFunction.java:43)
	at org.mozilla.javascript.InterfaceAdapter.invokeImpl(InterfaceAdapter.java:155)
	at org.mozilla.javascript.InterfaceAdapter.lambda$invoke$0(InterfaceAdapter.java:105)
	at org.mozilla.javascript.Context.call(Context.java:554)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:522)
	at org.mozilla.javascript.InterfaceAdapter.invoke(InterfaceAdapter.java:105)
	at org.mozilla.javascript.jdk18.VMBridge_jdk18$1.invoke(VMBridge_jdk18.java:126)
	at com.sun.proxy.$Proxy4.run(Unknown Source)
	at org.itxtech.mcl.script.ScriptManager.phaseLoad(ScriptManager.java:93)
	at org.itxtech.mcl.Loader.start(Loader.java:126)
	at org.itxtech.mcl.Loader.main(Loader.java:53)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.itxtech.mcl.component.Config$Package.getName(Config.java:101)
	at org.itxtech.mcl.component.Config$Package.getBasename(Config.java:105)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	... 18 more

**Comment by PeratX** [comment]
package id错误，应该为 `net.mamoe:mirai-login-solver-selenium`
