### ISSUE TITLE
idea插件在2021.1 RC无法正常运行

### ISSUE THREAD

**Issue by lliioollcn** [mamoe/mirai-console#323]
`java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/intellij/testFramework/TemporaryDirectoryKt
	at com.intellij.openapi.application.impl.LaterInvocator.invokeAndWait(LaterInvocator.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:428)
	at net.mamoe.mirai.console.intellij.creator.tasks.TaskUtilsKt.invokeAndWait(TaskUtils.kt:47)
	at net.mamoe.mirai.console.intellij.creator.tasks.TaskUtilsKt.runWriteActionAndWait(TaskUtils.kt:52)
	at net.mamoe.mirai.console.intellij.creator.tasks.TaskUtilsKt.runWriteActionAndWait$default(TaskUtils.kt:51)
	at net.mamoe.mirai.console.intellij.creator.build.GradleProjectCreator.createProject(ProjectCreator.kt:69)
	at net.mamoe.mirai.console.intellij.creator.build.GradleGroovyProjectCreator.createProject(ProjectCreator.kt:99)
	at net.mamoe.mirai.console.intellij.creator.tasks.CreateProjectTask.run(CreateProjectTask.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:998)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:497)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/intellij/testFramework/TemporaryDirectoryKt
	at net.mamoe.mirai.console.intellij.creator.tasks.TaskUtilsKt.writeChild(TaskUtils.kt:84)
	at net.mamoe.mirai.console.intellij.creator.build.GradleProjectCreator$createProject$1.invoke(ProjectCreator.kt:72)
	at net.mamoe.mirai.console.intellij.creator.build.GradleProjectCreator$createProject$1.invoke(ProjectCreator.kt:69)
	at net.mamoe.mirai.console.intellij.creator.tasks.TaskUtilsKt$runWriteActionAndWait$1$invoke$$inlined$runWriteAction$1.compute(actions.kt:9)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$runWriteAction$15(ApplicationImpl.java:968)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:947)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:968)
	at net.mamoe.mirai.console.intellij.creator.tasks.TaskUtilsKt$runWriteActionAndWait$1.invoke(TaskUtils.kt:150)
	at net.mamoe.mirai.console.intellij.creator.tasks.TaskUtilsKt$invokeAndWait$1$1.run(TaskUtils.kt:47)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$7(ApplicationImpl.java:428)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:134)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:133)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:189)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.intellij.testFramework.TemporaryDirectoryKt PluginClassLoader(plugin=PluginDescriptor(name=Mirai Console, id=net.mamoe.mirai-console, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IdeaIC2021.1\plugins\mirai-console-intellij, version=2.6-M1, package=null), packagePrefix=null, instanceId=68, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 39 more`

![图片](https://user-images.githubusercontent.com/44719954/113505232-0eac9800-9570-11eb-94bb-395bd7624614.png)

idea版本
![图片](https://user-images.githubusercontent.com/44719954/113505239-18ce9680-9570-11eb-8548-ac698cb32e15.png)

**Comment by Him188** [comment]
这看起来是 IJ 的问题, 请先使用稳定的 2020.3.3

**Comment by Him188** [comment]
[mirai-console-intellij-2.6-M2.zip](https://github.com/mamoe/mirai-console/files/6287193/mirai-console-intellij-2.6-M2.zip)

可以先使用这个版本 (下载后拖到 IDE 安装)
