### ISSUE TITLE
jdk8环境下自动退出

### ISSUE THREAD

**Issue by Tarocch1** [mamoe/mirai-console#36]
没有安装插件，使用的是AdoptOpenJDK-openjdk8-OpenJ9，运行wrapper闪退。

```
You are running Mirai-Console-Wrapper under D:\Program\test
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.4.6 | Newest Console-Pure Version: 0.4.6
Local Core Version: 0.34.0 | Newest Core Version: 0.34.0
Version check complete, starting Mirai
shadow-Protocol:D:\Program\test\content\mirai-core-qqandroid-jvm-0.34.0.jar
Console        :D:\Program\test\content\mirai-console-0.4.6.jar
Root           :D:\Program\test/
Exception in thread "Thread-9" java.lang.IllegalArgumentException: Encodings with multiple chars per byte are not supported
        at kotlin.io.ConsoleKt.readLine(Console.kt:156)
        at kotlin.io.ConsoleKt.readLine(Console.kt:153)
        at net.mamoe.mirai.console.pure.MiraiConsoleUIPure$1.invoke(MiraiConsoleUIPure.kt:48)
        at net.mamoe.mirai.console.pure.MiraiConsoleUIPure$1.invoke(MiraiConsoleUIPure.kt:25)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
 09:30:28 [INFO] [Mirai 0.4.6 Pkmon] Mirai-console now running under D:\Program\test
 09:30:28 [INFO] [Mirai 0.4.6 Pkmon] Get news in github: https://github.com/mamoe/mirai
 09:30:28 [INFO] [Mirai 0.4.6 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 09:30:28 [INFO] [Mirai 0.4.6 Pkmon] Powered by Mamoe Technologies and contributors
 09:30:28 [INFO] [Plugin Manager] 开始加载D:\Program\test/plugins/下的插件
 09:30:28 [INFO] [Plugin Manager] 加载了0个插件
 09:30:28 [INFO] [Mirai 0.4.6 Pkmon] Mirai-console 启动完成
 09:30:28 [INFO] [Mirai 0.4.6 Pkmon] "/login qqnumber qqpassword " to login a bot
 09:30:28 [INFO] [Mirai 0.4.6 Pkmon] "/login qq号 qq密码 " 来登录一个BOT
```

上述日志打完程序直接自动结束。

该问题在jdk11下不存在。

**Comment by Him188** [comment]
不是 console 问题，Kotlin `readLine` 不支持一个 byte 多个 char 的输入方式。请使用 JDK 11
