### ISSUE TITLE
使用login指令一直弹出输入验证码

### ISSUE THREAD

**Issue by JESVN** [mamoe/mirai-console#372]
![Snipaste_2021-06-22_10-05-22](https://user-images.githubusercontent.com/49424543/122851364-6d004000-d341-11eb-9b3c-c80ec1f0081d.png)
一直弹出这个输入验证码，无论输入的验证码的对错，我qq上登录保护啥的都关闭了的，请问这该怎么解决啊？

**Comment by Him188** [comment]
看看网络日志（bots/qq号/logs）

**Comment by xtyuns** [comment]
I ran into the same problem

this is my log, I replace my bot's ID inside with $QQ

```
[0m2021-06-22 15:49:25 V/Net $QQ: [BotSessionSyncer] No server list cached.[0m
[0m2021-06-22 15:49:25 V/Net $QQ: Send: wtlogin.login[0m
[0m2021-06-22 15:49:25 V/Net $QQ: Recv: wtlogin.login[0m
[0m2021-06-22 15:49:25 V/Net $QQ: Send: wtlogin.login[0m
[0m2021-06-22 15:49:25 V/Net $QQ: Recv: wtlogin.login[0m
[0m2021-06-22 15:49:37 V/Net $QQ: Send: wtlogin.login[0m
[0m2021-06-22 15:49:37 V/Net $QQ: Recv: wtlogin.login[0m
[91m2021-06-22 15:49:37 W/Net $QQ: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot($QQ), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot($QQ), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:247)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m
[0m2021-06-22 15:49:37 V/Net $QQ: [BotSessionSyncer] No server list cached.[0m
[0m2021-06-22 15:49:37 V/Net $QQ: Send: wtlogin.login[0m
[0m2021-06-22 15:49:37 V/Net $QQ: Recv: wtlogin.login[0m
[0m2021-06-22 15:49:37 V/Net $QQ: Send: wtlogin.login[0m
[0m2021-06-22 15:49:37 V/Net $QQ: Recv: wtlogin.login[0m
```

**Comment by Him188** [comment]
和 https://github.com/mamoe/mirai/issues/1352 一样

**Comment by JESVN** [comment]
![Snipaste_2021-06-22_16-28-28](https://user-images.githubusercontent.com/49424543/122891205-e9f9dc80-d376-11eb-929b-8eca39f7cfce.png)
@Him188
