### ISSUE TITLE
输入账号密码后报错

### ISSUE THREAD

**Issue by pyg2007** [mamoe/mirai-console#4]
报错如下：

>  19:43:28 [Bot Login]: login...
Exception in thread "DefaultDispatcher-worker-1" java.lang.NoSuchMethodError: kotlinx.serialization.internal.SerialClassDescImpl.<init>(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;I)V
        at net.mamoe.mirai.utils.SystemDeviceInfo$$serializer.<clinit>(SystemDeviceInfo.kt:43)
        at net.mamoe.mirai.utils.SystemDeviceInfo$Companion.serializer(SystemDeviceInfo.kt)
        at net.mamoe.mirai.utils.SystemDeviceInfoKt.loadAsDeviceInfo(SystemDeviceInfo.kt:31)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1$$special$$inlined$unaryPlus$1.invoke(BotConfigurationJvm.kt:222)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1$$special$$inlined$unaryPlus$1.invoke(BotConfigurationJvm.kt:160)
        at net.mamoe.mirai.qqandroid.QQAndroidBotBase.<init>(QQAndroidBot.kt:57)
        at net.mamoe.mirai.qqandroid.QQAndroidBot.<init>(QQAndroidBot.kt:38)
        at net.mamoe.mirai.qqandroid.QQAndroid.newBot(QQAndroid.kt:34)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1.invokeSuspend(DefaultCommands.kt:278)
        at net.mamoe.mirai.console.command.DefaultCommands$invoke$2$1.invoke(DefaultCommands.kt)
        at net.mamoe.mirai.console.command.AnonymousCommand.onCommand(Command.kt:124)
        at net.mamoe.mirai.console.command.CommandManager.runCommand$mirai_console(CommandManager.kt:55)
        at net.mamoe.mirai.console.MiraiConsole$CommandProcessor.processNextCommandLine(MiraiConsole.kt:149)
        at net.mamoe.mirai.console.MiraiConsole$CommandProcessor$processNextCommandLine$1.invokeSuspend(MiraiConsole.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)

**Comment by zhzRedstone** [comment]
更新下wapper试试。

**Comment by pyg2007** [comment]
已成功

**Comment by pyg2007** [comment]
更新后可以正常登陆
