### ISSUE TITLE
添加无终端启动支持

### ISSUE THREAD

**Issue by BoringCat** [mamoe/mirai-console#48]
是否可以考虑支持在无终端环境下运行，例如nohub或docker环境。
命令可以考虑使用参数传入
好处：
- 无人值守部署与运行
- docker化支持

<details>
  <summary>运行日志（nohub, install)</summary>

``` sh
/app # nohup java -jar mirai-console-wrapper-0.2.0-all.jar
nohup: appending output to nohup.out
/app # cat nohup.out 
You are running Mirai-Console-Wrapper under /app
Please select Console Type
请选择 Console 版本
=> Pure       : pure console
=> Graphical  : graphical UI except unix
=> Terminal   : [Not Supported Yet] console in unix
Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.Scanner.throwFor(Scanner.java:937)
	at java.base/java.util.Scanner.next(Scanner.java:1478)
	at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative(WrapperMain.kt:107)
	at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:89)
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/sh
   29 root      0:00 ps aux
/app # 
```

</details>
<details>
  <summary>运行日志（nohub, beforelogin)</summary>

``` sh
/app # nohup java -jar mirai-console-wrapper-0.2.0-all.jar
nohup: appending output to nohup.out
/app # cat nohup.out 
You are running Mirai-Console-Wrapper under /app
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Fetching Newest Console Version of Pure
Local Core Version: 0.36.1 | Newest Core Version: 0.36.1
Local Console-Pure Version: 0.4.8 | Newest Console-Pure Version: 0.4.8
Version check complete, starting Mirai
shadow-Protocol:/app/content/mirai-core-qqandroid-jvm-0.36.1.jar
Console        :/app/content/mirai-console-0.4.8.jar
Root           :/app/
 07:07:01 [INFO] [Mirai 0.4.8 Pkmon] Mirai-console now running under /app
 07:07:01 [INFO] [Mirai 0.4.8 Pkmon] Get news in github: https://github.com/mamoe/mirai
 07:07:01 [INFO] [Mirai 0.4.8 Pkmon] Mirai为开源项目，请自觉遵守开源项目协议
 07:07:01 [INFO] [Mirai 0.4.8 Pkmon] Powered by Mamoe Technologies and contributors
 07:07:01 [INFO] [Plugin Manager] 开始加载/app/plugins/下的插件
 07:07:01 [INFO] [Plugin Manager] 加载了0个插件
 07:07:01 [INFO] [Mirai 0.4.8 Pkmon] Mirai-console 启动完成
 07:07:01 [INFO] [Mirai 0.4.8 Pkmon] "/login qqnumber qqpassword " to login a bot
 07:07:01 [INFO] [Mirai 0.4.8 Pkmon] "/login qq号 qq密码 " 来登录一个BOT
/app # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 /bin/sh
  163 root      0:00 ps aux
/app # 
```

</details>

**Comment by liujiahua123123** [comment]
有一个docker实现 稍等我找下

**Comment by larvata** [comment]
能否通过启动参数或者配置文件初始化程序
目前似乎只能通过命令行交互式输入参数 
docker实现会很麻烦

**Comment by Him188** [comment]
目前可以通过传环境变量实现自动登录

**Comment by larvata** [comment]
@Him188 
请问有相关文档吗 
我在console和wrapper的源码里搜了下"env"
没找到相关的内容

**Comment by takayama-lily** [comment]
至少要有一个交互途径啊，因为有验证码设备锁之类的问题
（搞个web管理页面？）

**Comment by Him188** [comment]
> 至少要有一个交互途径啊，因为有验证码设备锁之类的问题
> （搞个web管理页面？）

功能不是你说就有的。

**Comment by Him188** [comment]
> 至少要有一个交互途径啊，因为有验证码设备锁之类的问题
> （搞个web管理页面？）

至少先阅读 README，再来问这个问题
