### ISSUE TITLE
无法启动图形界面版本

### ISSUE THREAD

**Issue by R-Josef** [mamoe/mirai-console#55]
我用这个指令来获得完整的错误追踪:
java -Djavafx.verbose=true -Dprism.verbose=true -jar mirai-console-wrapper-0.3.0.jar
然后得到了这些报错:
```
You are running Mirai-Console-Wrapper under C:\Users\Feng\Desktop\mirai-gui
Starting Mirai Console Graphical, reset by clear /content/
Starting version check...
Fetching Newest Core Version ..
Fetching Newest Console Version of Graphical
Local Core Version: 0.37.3 | Newest Core Version: 0.37.3
Local Console-Graphical Version: 0.0.7 | Newest Console-Graphical Version: 0.0.7
Version check complete, starting Mirai
shadow-Protocol:C:\Users\Feng\Desktop\mirai-gui\content\mirai-core-qqandroid-jvm-0.37.3.jar
Console        :C:\Users\Feng\Desktop\mirai-gui\content\mirai-console-graphical-0.0.7.jar
Root           :C:\Users\Feng\Desktop\mirai-gui/
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-console-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-console-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-datetime-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-datetime-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-debug-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-debug-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-errorhandling-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-errorhandling-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-file-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-file-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-file-l1-2-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-file-l1-2-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-file-l2-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-file-l2-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-handle-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-handle-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-heap-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-heap-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-interlocked-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-interlocked-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-libraryloader-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-libraryloader-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-localization-l1-2-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-localization-l1-2-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-memory-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-memory-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-namedpipe-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-namedpipe-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-processenvironment-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-processenvironment-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-processthreads-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-processthreads-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-processthreads-l1-1-1.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-processthreads-l1-1-1.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-profile-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-profile-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-rtlsupport-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-rtlsupport-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-string-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-string-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-synch-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-synch-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-synch-l1-2-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-synch-l1-2-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-sysinfo-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-sysinfo-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-timezone-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-timezone-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-core-util-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-core-util-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-conio-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-conio-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-convert-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-convert-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-environment-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-environment-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-filesystem-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-filesystem-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-heap-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-heap-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-locale-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-locale-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-math-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-math-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-multibyte-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-multibyte-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-private-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-private-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-process-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-process-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-runtime-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-runtime-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-stdio-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-stdio-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-string-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-string-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-time-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-time-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\api-ms-win-crt-utility-l1-1-0.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\api-ms-win-crt-utility-l1-1-0.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\ucrtbase.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\ucrtbase.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\vcruntime140.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\vcruntime140.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\msvcp140.dll
Loaded C:\Program Files\Java\jdk-13.0.2\bin\msvcp140.dll from java.library.path
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\concrt140.dll
Loaded C:\WINDOWS\system32\concrt140.dll from java.library.path
Prism pipeline init order: d3d sw
Using Double Precision Marlin Rasterizer
Using dirty region optimizations
Not using texture mask for primitives
Not forcing power of 2 sizes for textures
Using hardware CLAMP_TO_ZERO mode
Opting in for HiDPI pixel scaling
Prism pipeline name = com.sun.prism.d3d.D3DPipeline
GraphicsPipeline.createPipeline failed for com.sun.prism.d3d.D3DPipeline
java.lang.ClassNotFoundException: com.sun.prism.d3d.D3DPipeline
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:333)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:830)
*** Fallback to Prism SW pipeline
Prism pipeline name = com.sun.prism.sw.SWPipeline
WARNING: java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Feng\Desktop\mirai-gui\bin\prism_sw.dll
GraphicsPipeline.createPipeline failed for com.sun.prism.sw.SWPipeline
java.lang.UnsatisfiedLinkError: no prism_sw in java.library.path: [C:\Program Files\Java\jdk-13.0.2\bin, C:\WINDOWS\Sun\Java\bin, C:\WINDOWS\system32, C:\WINDOWS, E:\OracleDB\bin, C:\Windows\system32, C:\Windows, C:\Windows\System32\Wbem, C:\Windows\System32\WindowsPowerShell\v1.0\, C:\Windows\System32\OpenSSH\, C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR, C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common, C:\Program Files\PuTTY\, C:\Program Files\apache-maven-3.6.3\bin, C:\Program Files\Git\cmd, C:\Program Files\ffmpeg\bin, C:\Program Files (x86)\rtmpdump, C:\Program Files\TortoiseSVN\bin, C:\Program Files\Java\jdk-13.0.2\bin, C:\Program Files\Java\jdk1.8.0_241\bin, C:\Program Files (x86)\Common Files\Oracle\Java\javapath, C:\Program Files (x86)\PixivUtil2, C:\MinGW\bin, C:\Program Files\youtube-dl, C:\WINDOWS\system32, C:\WINDOWS, C:\WINDOWS\System32\Wbem, C:\WINDOWS\System32\WindowsPowerShell\v1.0\, C:\WINDOWS\System32\OpenSSH\, C:\Program Files\dotnet\, C:\Program Files\MongoDB\Server\4.2\bin, C:\Program Files\Gradle\bin, C:\Users\Feng\AppData\Local\Microsoft\WindowsApps, C:\Program Files\JetBrains\IntelliJ IDEA 2020.1\bin, C:\Users\Feng\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\Scripts, C:\Users\Feng\.dotnet\tools, C:\Program Files\JetBrains\IntelliJ IDEA 2020.1\bin, ., ., .]
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:806)
        at java.base/java.lang.System.loadLibrary(System.java:1909)
        at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:163)
        at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:53)
        at com.sun.prism.sw.SWPipeline.lambda$static$0(SWPipeline.java:42)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at com.sun.prism.sw.SWPipeline.<clinit>(SWPipeline.java:41)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:333)
        at com.sun.prism.GraphicsPipeline.createPipeline(GraphicsPipeline.java:218)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:91)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        at java.base/java.lang.Thread.run(Thread.java:830)
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
        ... 1 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.mamoe.mirai.console.wrapper.WrapperMain.start(WrapperMain.kt:157)
        at net.mamoe.mirai.console.wrapper.WrapperMain.preStartInNonNative(WrapperMain.kt:134)
        at net.mamoe.mirai.console.wrapper.WrapperMain.main(WrapperMain.kt:90)
Caused by: java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:272)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:678)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by mzdluo123** [comment]
请使用QQ群内的一键安装包，它为你准备好了启动mirai所有功能所需的一切环境。
未来我们将会吧安装包上传到GitHub

**Comment by daofeng2015** [comment]
目前gui版本还不完善,请使用pure版本
