### ISSUE TITLE
当多个插件有相同的jar依赖时触发java.lang.LinkageError

### ISSUE THREAD

**Issue by ssttkkl** [mamoe/mirai-console#76]
现在有两个插件同时`implementation("com.beust:klaxon:5.2")`，放在一起使用时会抛出`java.lang.LinkageError`

```
Exception in thread "DefaultDispatcher-worker-1" java.lang.LinkageError: loader net.mamoe.mirai.console.plugins.PluginClassLoader @55795845 attempted duplicate interface definition for com.beust.klaxon.internal.ConverterFinder. (com.beust.klaxon.internal.ConverterFinder is in unnamed module of loader net.mamoe.mirai.console.plugins.PluginClassLoader @1bcf67e8, parent loader net.mamoe.mirai.console.wrapper.MiraiClassLoader @d62fe5b)
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
        at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
        at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
        at net.mamoe.mirai.console.plugins.PluginClassLoader.findClass(PluginsLoader.kt:127)
        at net.mamoe.mirai.console.plugins.PluginsLoader.loadDependentClass(PluginsLoader.kt:83)
        at net.mamoe.mirai.console.plugins.PluginClassLoader.findClass(PluginsLoader.kt:123)
        at net.mamoe.mirai.console.plugins.PluginClassLoader.findClass(PluginsLoader.kt:111)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at com.ssttkkl.miraiplugin.KeywordReplyPlus$onLoad$1.invokeSuspend(KeywordReplyPlus.kt:31)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by liujiahua123123** [comment]
他应该解决了
