### ISSUE TITLE
部分文件无法下载

### ISSUE THREAD

**Issue by iceprosurface** [mamoe/mirai-console#92]
国内源无法下载

主要是这个文件，一直都是 524
https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4

```
Local Core Version: 0.0.0 | Newest STABLE Core Version: 1.0.2
Updating shadowed-core from V0.0.0 -> V1.0.2
Mirai Downloader
[Mirai国内镜像] 感谢崔Cloud慷慨提供免费的国内储存分发
Progress: #########################################################  | Failed##
#####################  | FailedFailed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4 reason Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4

Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4 reason Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4
java.io.IOException: Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at net.mamoe.mirai.console.wrapper.MiraiDownloaderImpl$downloadTask$2.invokeSuspend(MiraiDownloader.kt:87)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4 reason Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
Please Seek For Help
java.io.IOException: Server returned HTTP response code: 524 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
```

> 我找个海外服试试能不能吧包搞下来

**Comment by pwinner** [comment]
我刚好也遇到了这个问题，并且我是海外服务器，应该是镜像挂了

**Comment by chengpengzhao** [comment]
我昨天晚上还可以下，今天试就不行了
