### ISSUE TITLE
mirai国内源无法正常下载

### ISSUE THREAD

**Issue by khjxiaogu** [mamoe/mirai-console#95]
mirai需求强制更新，但是每次自动下载更新都会显示
```
[Mirai国内镜像] 感谢崔Cloud慷慨提供免费的国内储存分发
Progress: ########################################  | Failed
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-console-graphical/mirai-console-graphical-0.0.7.mp4 reason Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console-graphical/mirai-console-graphical-0.0.7.mp4
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4 reason Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
java.io.IOException: Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console-graphical/mirai-console-graphical-0.0.7.mp4
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at net.mamoe.mirai.console.wrapper.MiraiDownloaderImpl$downloadTask$2.invokeSuspend(MiraiDownloader.kt:87)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-console-graphical/mirai-console-graphical-0.0.7.mp4 reason Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console-graphical/mirai-console-graphical-0.0.7.mp4java.io.IOException: Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4

Please Seek For Help
```
现在我的服务都被迫停摆了，请尽块解决或者提供其他下载渠道（比如github release)

**Comment by Him188** [comment]
使用1.3.0版本wrapper，并详细阅读Readme
