### ISSUE TITLE
在界面login的时候出现异常，疑为库版本问题

### ISSUE THREAD

**Issue by khjxiaogu** [mamoe/mirai-console#96]
Graphical版本0.0.7 core版本qqandroid 1.0.2
登录时出现以下异常
```
[NETWORK ERROR] java.lang.NoClassDefFoundError: net/mamoe/mirai/network/BotNetworkHandler
	at net.mamoe.mirai.console.command.DefaultCommands$login$$inlined$Bot$lambda$2.invoke(DefaultCommands.kt:35)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.getLogger(QQAndroidBotNetworkHandler.kt:53)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler.closeEverythingAndRelogin(QQAndroidBotNetworkHandler.kt:147)
	at net.mamoe.mirai.qqandroid.network.QQAndroidBotNetworkHandler$closeEverythingAndRelogin$1.invokeSuspend(QQAndroidBotNetworkHandler.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.network.BotNetworkHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at net.mamoe.mirai.console.wrapper.MiraiClassLoader.findClass(WrapperMain.kt:278)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 more
```
经查看实际上这个类在net.mamoe.mirai.qqandroid.network包里面，是否遗漏了更新？

**Comment by Him188** [comment]
使用1.3.0的wrapper

**Comment by Him188** [comment]
console 正在重构，短时间内不会更新 graphical
