### ISSUE TITLE
mirai 无法启动，原因无法拉取最新Mirai core 文件。

### ISSUE THREAD

**Issue by expoli** [mamoe/mirai-console#99]
报错信息

```java
java -jar ./mirai-console-wrapper-1.0.0.jar
You are running Mirai-Console-Wrapper under opt/mirai-console
All additional libraries are located at opt/mirai-console/libraries
Starting Mirai Console Pure, reset by clear /content/
Starting version check...
Fetching Newest Core Version .. 
Fetching Newest Console Version of Pure
Local Console-Pure Version: 0.0.0 | Newest STABLE Console-Pure Version: 0.5.2
Updating Console-Pure from V0.0.0 -> V0.5.2
Local Core Version: 0.0.0 | Newest STABLE Core Version: 1.0.2
Updating shadowed-core from V0.0.0 -> V1.0.2
Mirai Downloader
[Mirai国内镜像] 感谢崔Cloud慷慨提供免费的国内储存分发
Progress: ##########################################  | Failed
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4 reason Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4
######################################  | Failed
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4 reason Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
java.io.IOException: Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at net.mamoe.mirai.console.wrapper.MiraiDownloaderImpl$downloadTask$2.invokeSuspend(MiraiDownloader.kt:87)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4 reason Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-console/mirai-console-0.5.2.mp4
Please Seek For Help
java.io.IOException: Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at net.mamoe.mirai.console.wrapper.MiraiDownloaderImpl$downloadTask$2.invokeSuspend(MiraiDownloader.kt:87)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Failed to download resources from https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4 reason Server returned HTTP response code: 502 for URL: https://pan.jasonczc.cn/?/mirai/mirai-core-qqandroid/mirai-core-qqandroid-1.0.2.mp4
```

**Comment by Him188** [comment]
使用更新的wrapper

**Comment by expoli** [comment]
> 使用更新的wrapper

你好，我找了一下，实在console的release界面下载吗？
抱歉我没找到相关的jar下载地址。

**Comment by Him188** [comment]
> > 使用更新的wrapper
> 
> 你好，我找了一下，实在console的release界面下载吗？
> 抱歉我没找到相关的jar下载地址。


https://github.com/project-mirai/mirai-console-wrapper
